In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW10 = pd.read_csv('GW10.csv')
GW10

HomeTeam          AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  \
0  Crystal Palace         Tottenham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
1         Chelsea         Brentford  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
2         Arsenal  Sheffield United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
3     Bournemouth           Burnley  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
4          Wolves         Newcastle  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
5        West Ham           Everton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
6     Aston Villa             Luton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
7        Brighton            Fulham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
8       Liverpool     Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
9      Man United          Man City  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   

   AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.6  -1.300000  -0.250000   
1 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.8   0.000000  -0.450000   
2 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       2.2   2.000000   1.450000   
3 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4  -0.100000   0.000000   
4 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.0  -0.600000  -0.600000   
5 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4   0.400000   0.450000   
6 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       1.6   1.644444   1.544444   
7 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0   0.500000   0.400000   
8 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       1.2   1.000000   1.150000   
9 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0  -0.300000  -0.450000   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5   SDiff10  \
0     -1.4 -1.600000 -0.750000      0.6  0.300000 -0.400000    -9.8 -4.700000   
1      0.4 -0.100000 -0.350000     -0.6 -0.200000  0.200000    -4.0 -0.300000   
2      1.4  1.500000  1.650000     -2.6 -1.600000 -0.900000     3.4  5.000000   
3     -0.2 -0.200000 -0.050000      0.2 -0.400000 -0.050000     0.2  0.500000   
4     -2.0 -1.400000 -1.450000      1.0  1.000000  0.650000    -5.2 -2.700000   
5      0.0  0.700000  0.500000      1.2  0.400000  0.200000    -4.8 -3.100000   
6      1.8  1.611111  1.061111     -0.6 -0.488889 -0.888889     2.2  2.122222   
7      1.2  1.400000  0.900000      1.4  0.300000  0.300000    -2.0  3.800000   
8      1.4  1.300000  1.050000      0.0  0.000000 -0.400000     5.0  7.500000   
9     -0.4 -0.600000 -0.900000      0.2  0.600000  0.200000     1.2  0.700000   

    SDiff20  STDiff5  STDiff10  STDiff20  FDiff5   FDiff10   FDiff20  CDiff5  \
0 -1.900000     -3.8 -2.400000 -1.150000    -2.8  0.000000 -0.150000    -4.0   
1  1.450000      0.4 -0.100000 -0.050000    -1.2 -0.900000 -0.500000    -1.4   
2  5.300000      1.4  2.400000  2.950000    -0.6 -1.900000 -1.300000     4.6   
3  0.200000      0.6  0.800000  0.700000     4.6  3.200000  1.500000    -1.8   
4 -4.350000     -3.8 -3.000000 -2.550000     5.2  2.000000  2.150000    -1.6   
5 -3.050000      0.4 -1.000000 -0.600000    -0.6 -0.300000 -1.250000     1.2   
6  0.122222      3.4  3.455556  2.105556    -0.4 -0.211111 -1.061111     0.8   
7  6.050000      0.4  2.800000  2.750000     1.4  2.300000  1.850000    -2.4   
8  6.300000      1.2  1.600000  1.700000    -0.2  0.400000  0.400000     1.2   
9  3.400000     -1.8 -1.000000 -0.150000     1.2  2.000000  1.650000     1.0   

    CDiff10   CDiff20  YDiff5   YDiff10   YDiff20  RDiff5  RDiff10  RDiff20  \
0 -1.900000  0.000000    -1.4 -1.500000 -0.950000    -0.2     -0.1    -0.10   
1  0.600000  0.750000    -0.2  0.200000  0.550000     0.0      0.0     0.00   
2  4.200000  2.500000    -0.8 -1.200000 -1.050000    -0.2      0.0     0.00   
3 -1.500000 -1.250000    -0.4 -0.200000 -0.150000     0.0     -0.2    -0.15   
4 -0.700000 -1.750000     1.4  0.600000  1.200000     0.4      0.3     0.20   
5 -1.000000  0.050000     1.0  0.600000  0.000000    -0

In [3]:
GW10 = GW10[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW10

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0      -1.6  -1.300000  -0.250000     -1.4 -1.600000 -0.750000      0.6   
1       0.8   0.000000  -0.450000      0.4 -0.100000 -0.350000     -0.6   
2       2.2   2.000000   1.450000      1.4  1.500000  1.650000     -2.6   
3      -0.4  -0.100000   0.000000     -0.2 -0.200000 -0.050000      0.2   
4      -1.0  -0.600000  -0.600000     -2.0 -1.400000 -1.450000      1.0   
5      -0.4   0.400000   0.450000      0.0  0.700000  0.500000      1.2   
6       1.6   1.644444   1.544444      1.8  1.611111  1.061111     -0.6   
7       0.0   0.500000   0.400000      1.2  1.400000  0.900000      1.4   
8       1.2   1.000000   1.150000      1.4  1.300000  1.050000      0.0   
9       0.0  -0.300000  -0.450000     -0.4 -0.600000 -0.900000      0.2   

   GCDiff10  GCDiff20  SDiff5   SDiff10   SDiff20  STDiff5  STDiff10  \
0  0.300000 -0.400000    -9.8 -4.700000 -1.900000     -3.8 -2.400000   
1 -0.200000  0.200000    -4.0 -0.300000  1.450000      0.4 -0.100000   
2 -1.600000 -0.900000     3.4  5.000000  5.300000      1.4  2.400000   
3 -0.400000 -0.050000     0.2  0.500000  0.200000      0.6  0.800000   
4  1.000000  0.650000    -5.2 -2.700000 -4.350000     -3.8 -3.000000   
5  0.400000  0.200000    -4.8 -3.100000 -3.050000      0.4 -1.000000   
6 -0.488889 -0.888889     2.2  2.122222  0.122222      3.4  3.455556   
7  0.300000  0.300000    -2.0  3.800000  6.050000      0.4  2.800000   
8  0.000000 -0.400000     5.0  7.500000  6.300000      1.2  1.600000   
9  0.600000  0.200000     1.2  0.700000  3.400000     -1.8 -1.000000   

   STDiff20  FDiff5   FDiff10   FDiff20  CDiff5   CDiff10   CDiff20  YDiff5  \
0 -1.150000    -2.8  0.000000 -0.150000    -4.0 -1.900000  0.000000    -1.4   
1 -0.050000    -1.2 -0.900000 -0.500000    -1.4  0.600000  0.750000    -0.2   
2  2.950000    -0.6 -1.900000 -1.300000     4.6  4.200000  2.500000    -0.8   
3  0.700000     4.6  3.200000  1.500000    -1.8 -1.500000 -1.250000    -0.4   
4 -2.550000     5.2  2.000000  2.150000    -1.6 -0.700000 -1.750000     1.4   
5 -0.600000    -0.6 -0.300000 -1.250000     1.2 -1.000000  0.050000     1.0   
6  2.105556    -0.4 -0.211111 -1.061111     0.8  0.122222 -0.227778     1.4   
7  2.750000     1.4  2.300000  1.850000    -2.4  0.100000  0.200000     1.2   
8  1.700000    -0.2  0.400000  0.400000     1.2  2.900000  2.650000    -0.8   
9 -0.150000     1.2  2.000000  1.650000     1.0  1.000000  1.250000    -1.2   

    YDiff10   YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  \
0 -1.500000 -0.950000    -0.2     -0.1    -0.10   0   3            0   
1  0.200000  0.550000     0.0      0.0     0.00   1   3            0   
2 -1.200000 -1.050000    -0.2      0.0     0.00   1   0            0   
3 -0.200000 -0.150000     0.0     -0.2    -0.15   0   0            0   
4  0.600000  1.200000     0.4      0.3     0.20   3   3            0   
5  0.600000  0.000000    -0.2      0.0    -0.10   0   0            0   
6  0.933333  0.783333     0.0      0.0     0.00   3   1            0   
7  1.000000  0.750000     0.0     -0.2    -0.10   0   0            0   
8 -1.000000 -0.650000     0.2      0.2     0.10   3   1            0   
9  0.400000  0.600000    -0.4     -0.2    -0.10   3   3            0   

   AWinStreak3  HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  \
0            1            0            0             0             0   
1            0            0            0             0             0   
2            0            0            0             0             1   
3            0            0            0             1             0   
4            0            0            0             0             0   
5            0            0            0             0             0   
6            0            0            0             0             0   
7            0            0            0             0             0   
8            0            0            0             0             0   
9

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW10_predictions = np.argmax(diff_model.predict(GW10), axis=1)
GW10_predictions

1/1 [==============================] - 0s 451ms/step


array([0, 2, 2, 2, 0, 2, 2, 2, 2, 2], dtype=int64)

In [7]:
diff_model.predict(GW10)

1/1 [==============================] - 0s 37ms/step


array([[4.08917308e-01, 2.38660067e-01, 3.48772317e-01, 8.25106545e-05,
        4.84322918e-05, 7.13438494e-05, 2.44247385e-05, 4.31794797e-05,
        1.38991629e-04, 3.32865820e-05, 4.68037033e-05, 6.78653305e-05,
        5.82549255e-05, 4.62800890e-05, 6.56425982e-05, 4.24632854e-05,
        6.59881916e-05, 5.88107359e-05, 4.05344435e-05, 5.90927921e-05,
        5.47098862e-05, 4.73972468e-05, 5.11254366e-05, 4.18622440e-05,
        3.86469692e-05, 9.55174401e-05, 2.68916683e-05, 5.91684693e-05,
        8.33895319e-05, 2.30693258e-05, 4.70585510e-05, 4.76610512e-05,
        7.95600645e-05, 3.73422190e-05, 8.38234409e-05, 4.00201970e-05,
        3.79915655e-05, 3.91789363e-05, 2.28339832e-05, 5.08745616e-05,
        6.15616300e-05, 3.55169832e-05, 4.73235341e-05, 4.95555869e-05,
        8.03588337e-05, 4.60247611e-05, 2.93148278e-05, 5.71270866e-05,
        4.58733193e-05, 6.55246404e-05, 6.07991715e-05, 2.39476158e-05,
        6.58782810e-05, 7.92118153e-05, 3.35778350e-05, 7.822642

In [8]:
GW10_predictions_2 = np.argmax(diff_model_2.predict(GW10), axis=1)
GW10_predictions_2

1/1 [==============================] - 0s 103ms/step


array([0, 2, 2, 2, 0, 2, 2, 2, 2, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW10)

1/1 [==============================] - 0s 33ms/step


array([[0.41708127, 0.24039069, 0.34252805],
       [0.25227043, 0.24073714, 0.50699246],
       [0.05335711, 0.14123867, 0.80540407],
       [0.33629715, 0.24510147, 0.4186014 ],
       [0.52308387, 0.29748562, 0.17943043],
       [0.2910994 , 0.2595971 , 0.44930348],
       [0.15593655, 0.20945357, 0.6346098 ],
       [0.1535754 , 0.19930167, 0.6471229 ],
       [0.06933588, 0.17966814, 0.75099593],
       [0.26829472, 0.28964794, 0.4420573 ]], dtype=float32)

In [10]:
GW10_predictions_3 = np.argmax(diff_model_3.predict(GW10), axis=1)
GW10_predictions_3

1/1 [==============================] - 0s 109ms/step


array([2, 2, 2, 2, 0, 2, 2, 2, 2, 0], dtype=int64)

In [11]:
diff_model_3.predict(GW10)

1/1 [==============================] - 0s 104ms/step


array([[0.3736128 , 0.24167816, 0.38470897],
       [0.30319914, 0.27616745, 0.42063338],
       [0.08627637, 0.17422463, 0.73949903],
       [0.28521895, 0.31688422, 0.39789692],
       [0.49984473, 0.26737082, 0.23278444],
       [0.29271403, 0.24287777, 0.46440816],
       [0.22958934, 0.21795492, 0.5524557 ],
       [0.08821645, 0.19356766, 0.7182159 ],
       [0.08757335, 0.18333882, 0.7290879 ],
       [0.34375742, 0.3235587 , 0.33268386]], dtype=float32)