In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW11 = pd.read_csv('GW11.csv')
GW11

HomeTeam        AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  \
0            Fulham      Man United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
1         Brentford        West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
2           Burnley  Crystal Palace  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
3           Everton        Brighton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
4          Man City     Bournemouth  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
5  Sheffield United          Wolves  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
6         Newcastle         Arsenal  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
7     Nott'm Forest     Aston Villa  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
8             Luton       Liverpool  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
9         Tottenham         Chelsea  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   

   AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.8       -0.3      -0.60   
1 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6       -0.1       0.10   
2 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4       -0.8      -0.60   
3 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.8       -0.7      -0.65   
4 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       1.2        1.8       1.55   
5 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.8       -1.1      -0.80   
6 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0       -0.7      -0.20   
7 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -2.0       -1.2      -1.05   
8 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.2       -1.8      -1.85   
9 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       1.2        1.4       0.95   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5  SDiff10  \
0     -0.2      -0.2     -0.10      0.0       0.0      0.40    -2.4     -4.5   
1      0.4       0.0     -0.20     -0.8      -0.5     -0.60     1.8      2.6   
2      0.4       0.0     -0.30      1.2       1.2      0.70    -1.8     -3.1   
3      0.0      -1.3     -1.05     -1.4      -0.5     -0.25     4.2     -0.5   
4      0.8       1.4      1.35     -1.8      -1.4     -1.15     2.8      4.8   
5     -1.2      -0.6     -0.55      2.8       1.2      0.65    -0.2     -3.3   
6      0.8       0.3      0.15      0.0       0.3     -0.05     1.8     -0.4   
7     -2.4      -1.6     -0.75      0.8       0.1      0.60    -4.8     -4.2   
8     -1.0      -1.4     -1.60      0.8       1.1      0.85    -7.2     -5.4   
9      0.2       0.9      0.90     -0.4      -0.2      0.20     3.8      3.8   

   SDiff20  STDiff5  STDiff10  STDiff20  FDiff5  FDiff10  FDiff20  CDiff5  \
0    -6.90     -0.4      -1.3     -2.45     1.8      0.1     0.15    -1.2   
1     0.70      0.6       0.9      0.30     1.0      0.1     0.60    -0.6   
2    -2.45      0.0      -1.5     -0.95     0.0     -0.7    -0.55    -0.6   
3    -2.45      0.8      -1.5     -1.40    -2.8     -1.0    -1.40    -0.4   
4     3.55      2.0       2.9      2.25    -6.0     -5.3    -3.40     0.0   
5    -2.30     -1.8      -0.9     -1.10    -4.2     -1.8    -2.30    -1.4   
6     1.65      2.2       0.7      0.40     0.4      2.0     1.45    -1.8   
7    -3.60     -3.0      -2.5     -1.60     0.2     -0.2     1.15    -3.0   
8    -5.10     -3.4      -3.1     -3.05    -1.2      0.3    -0.10    -1.8   
9     1.75      0.6       1.7      1.30     2.0      0.6     1.25     1.2   

   CDiff10  CDiff20  YDiff5  YDiff10  YDiff20  RDiff5  RDiff10  RDiff20  H1  \
0     -1.9    -1.35    -0.6     -0.4    -0.45     0.0      0.2     0.10   1   
1      0.0    -0.45     1.4      0.3     0.55     0.0     -0.1    -0.05   3   
2      0.9     0.05     0.4      0.6     0.35     0.2      0.3     0.20   0   
3     -0.4    -0.50    -1.0     -1.0    -0.85     0.2      0.1     0.15   3   
4      1.4     1.35     0.8      0.1    -0.35     0.2      0.1     0.05   3   
5     -0.6    -0.85    -0.8     -0.3    -0.50    -0.4     -0.2    -0.10   0   
6     -3.4    -0.35   

In [3]:
GW11 = GW11[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW11

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0      -0.8       -0.3      -0.60     -0.2      -0.2     -0.10      0.0   
1       0.6       -0.1       0.10      0.4       0.0     -0.20     -0.8   
2      -0.4       -0.8      -0.60      0.4       0.0     -0.30      1.2   
3       0.8       -0.7      -0.65      0.0      -1.3     -1.05     -1.4   
4       1.2        1.8       1.55      0.8       1.4      1.35     -1.8   
5      -1.8       -1.1      -0.80     -1.2      -0.6     -0.55      2.8   
6       0.0       -0.7      -0.20      0.8       0.3      0.15      0.0   
7      -2.0       -1.2      -1.05     -2.4      -1.6     -0.75      0.8   
8      -1.2       -1.8      -1.85     -1.0      -1.4     -1.60      0.8   
9       1.2        1.4       0.95      0.2       0.9      0.90     -0.4   

   GCDiff10  GCDiff20  SDiff5  SDiff10  SDiff20  STDiff5  STDiff10  STDiff20  \
0       0.0      0.40    -2.4     -4.5    -6.90     -0.4      -1.3     -2.45   
1      -0.5     -0.60     1.8      2.6     0.70      0.6       0.9      0.30   
2       1.2      0.70    -1.8     -3.1    -2.45      0.0      -1.5     -0.95   
3      -0.5     -0.25     4.2     -0.5    -2.45      0.8      -1.5     -1.40   
4      -1.4     -1.15     2.8      4.8     3.55      2.0       2.9      2.25   
5       1.2      0.65    -0.2     -3.3    -2.30     -1.8      -0.9     -1.10   
6       0.3     -0.05     1.8     -0.4     1.65      2.2       0.7      0.40   
7       0.1      0.60    -4.8     -4.2    -3.60     -3.0      -2.5     -1.60   
8       1.1      0.85    -7.2     -5.4    -5.10     -3.4      -3.1     -3.05   
9      -0.2      0.20     3.8      3.8     1.75      0.6       1.7      1.30   

   FDiff5  FDiff10  FDiff20  CDiff5  CDiff10  CDiff20  YDiff5  YDiff10  \
0     1.8      0.1     0.15    -1.2     -1.9    -1.35    -0.6     -0.4   
1     1.0      0.1     0.60    -0.6      0.0    -0.45     1.4      0.3   
2     0.0     -0.7    -0.55    -0.6      0.9     0.05     0.4      0.6   
3    -2.8     -1.0    -1.40    -0.4     -0.4    -0.50    -1.0     -1.0   
4    -6.0     -5.3    -3.40     0.0      1.4     1.35     0.8      0.1   
5    -4.2     -1.8    -2.30    -1.4     -0.6    -0.85    -0.8     -0.3   
6     0.4      2.0     1.45    -1.8     -3.4    -0.35     0.2      1.2   
7     0.2     -0.2     1.15    -3.0     -2.3    -2.10     0.6      0.4   
8    -1.2      0.3    -0.10    -1.8     -1.1    -0.90     0.0     -0.1   
9     2.0      0.6     1.25     1.2      0.4     0.30    -0.2      0.0   

   YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0    -0.45     0.0      0.2     0.10   1   0            0            0   
1     0.55     0.0     -0.1    -0.05   3   0            0            0   
2     0.35     0.2      0.3     0.20   0   0            0            0   
3    -0.85     0.2      0.1     0.15   3   1            0            0   
4    -0.35     0.2      0.1     0.05   3   3            0            0   
5    -0.50    -0.4     -0.2    -0.10   0   1            0            0   
6     0.55     0.0     -0.1    -0.05   1   3            0            0   
7     0.10     0.2      0.2     0.10   0   3            0            0   
8    -0.10    -0.4     -0.4    -0.20   0   3            0            0   
9     0.00     0.2      0.1     0.10   3   0            1            0   

   HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  HLossStreak3  \
0            0            0             0             0             0   
1            0            0             0             0             0   
2            0            0             1             0             1   
3            0            0             0             0             0   
4            0            0             0             0             0   
5            0            0             1             0             1   
6            0            0             0             0             0   
7            0            0             0             0             0   
8        

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW11_predictions = np.argmax(diff_model.predict(GW11), axis=1)
GW11_predictions

1/1 [==============================] - 1s 565ms/step


array([0, 2, 0, 1, 2, 0, 2, 0, 0, 2], dtype=int64)

In [7]:
diff_model.predict(GW11)

1/1 [==============================] - 0s 44ms/step


array([[4.89987880e-01, 2.30519682e-01, 2.11646259e-01, 5.31927973e-04,
        8.37613887e-04, 8.32638179e-04, 8.34954088e-04, 8.84474313e-04,
        9.94385220e-04, 1.07922312e-03, 1.15132763e-03, 9.49653797e-04,
        6.79433346e-04, 1.35276373e-03, 9.63529339e-04, 1.35305012e-03,
        1.68169313e-03, 5.63257898e-04, 8.93951219e-04, 8.95056000e-04,
        7.24828744e-04, 1.25955697e-03, 1.36063481e-03, 8.49342323e-04,
        7.72550295e-04, 1.28691655e-03, 7.55146262e-04, 1.09654141e-03,
        8.92664422e-04, 6.85591775e-04, 7.15058704e-04, 6.18918799e-04,
        1.16036041e-03, 1.01456174e-03, 8.35205778e-04, 1.19076238e-03,
        8.04822484e-04, 1.38408842e-03, 8.09859717e-04, 8.42770445e-04,
        6.00017374e-04, 1.12876017e-03, 9.44309228e-04, 4.63514909e-04,
        9.95519105e-04, 1.31022546e-03, 6.21697342e-04, 1.01036252e-03,
        8.53237987e-04, 1.10064948e-03, 7.96759035e-04, 1.00663560e-03,
        1.36141304e-03, 1.22027425e-03, 9.64573293e-04, 1.045817

In [8]:
GW11_predictions_2 = np.argmax(diff_model_2.predict(GW11), axis=1)
GW11_predictions_2

1/1 [==============================] - 0s 245ms/step


array([0, 2, 0, 0, 2, 0, 2, 0, 0, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW11)

1/1 [==============================] - 0s 42ms/step


array([[0.50943416, 0.26235512, 0.22821066],
       [0.2417185 , 0.2451162 , 0.5131653 ],
       [0.41284525, 0.2829838 , 0.30417097],
       [0.37831327, 0.28668842, 0.3349983 ],
       [0.06029995, 0.13681781, 0.8028822 ],
       [0.43262267, 0.31560373, 0.25177363],
       [0.30065876, 0.2104437 , 0.48889753],
       [0.51153034, 0.2522211 , 0.23624852],
       [0.6106798 , 0.24786523, 0.14145495],
       [0.16969903, 0.23917355, 0.59112746]], dtype=float32)

In [10]:
GW11_predictions_3 = np.argmax(diff_model_3.predict(GW11), axis=1)
GW11_predictions_3

1/1 [==============================] - 0s 154ms/step


array([0, 2, 0, 0, 2, 0, 2, 0, 0, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW11)

1/1 [==============================] - 0s 37ms/step


array([[0.47970515, 0.23131368, 0.28898123],
       [0.2646073 , 0.27855852, 0.45683414],
       [0.36246356, 0.3104013 , 0.32713506],
       [0.41179895, 0.255811  , 0.33239   ],
       [0.0961887 , 0.11839339, 0.7854179 ],
       [0.44465843, 0.3379928 , 0.21734871],
       [0.32293034, 0.25521383, 0.4218557 ],
       [0.51395017, 0.2622678 , 0.22378197],
       [0.5171673 , 0.23570253, 0.24713017],
       [0.23171893, 0.25955242, 0.5087287 ]], dtype=float32)