In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW12 = pd.read_csv('GW12.csv')
GW12

HomeTeam          AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  \
0          Wolves         Tottenham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
1         Arsenal           Burnley  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
2  Crystal Palace           Everton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
3      Man United             Luton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
4     Bournemouth         Newcastle  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
5     Aston Villa            Fulham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
6        Brighton  Sheffield United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
7       Liverpool         Brentford  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
8        West Ham     Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
9         Chelsea          Man City  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   

   AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.8       -1.3  -0.550000   
1 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       1.4        1.7   1.050000   
2 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0        0.1   0.500000   
3 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       1.4        0.9   1.304545   
4 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.6       -1.2  -0.850000   
5 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       1.2        1.3   0.700000   
6 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0        1.1   0.900000   
7 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4        0.8   0.750000   
8 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4        0.0   0.000000   
9 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.2       -1.0  -1.450000   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5  SDiff10  \
0      0.0      -0.7 -0.900000      0.2       0.7  0.000000    -4.0     -6.2   
1      1.6       1.3  1.200000     -1.8      -1.6 -0.650000     2.8      3.5   
2     -0.4      -0.2  0.200000      0.2      -0.1 -0.400000    -4.8     -3.2   
3      0.0       0.2  0.390909     -0.6      -0.1 -0.809091     3.0      2.7   
4     -1.4      -1.4 -1.400000      2.4       1.6  0.900000    -3.6     -2.7   
5      2.0       1.7  0.650000     -0.2      -0.6 -0.400000     2.8      3.6   
6      0.4       1.1  1.450000     -0.2      -1.0 -0.350000     1.8      4.6   
7     -0.2       0.6  0.900000      0.0      -0.3  0.000000     4.4      3.9   
8      0.4       0.6  0.350000      0.8       0.6  0.250000     1.6      0.2   
9      0.0      -0.9 -1.050000      0.2       0.3  0.750000    -2.8     -2.0   

    SDiff20  STDiff5  STDiff10  STDiff20  FDiff5  FDiff10   FDiff20  CDiff5  \
0 -4.500000     -0.6      -2.4 -2.200000     3.8      2.5  2.550000     0.4   
1  2.200000      1.2       2.0  1.700000     0.0     -1.2 -0.350000     0.0   
2 -1.700000     -1.8      -0.7 -0.700000     0.2      0.2 -0.100000     1.2   
3  5.031818      2.0       2.5  3.204545    -0.8     -1.2 -0.804545     2.0   
4 -4.300000     -1.8      -1.6 -1.850000    -0.4      1.4  0.000000     1.4   
5  2.500000      1.8       2.1  1.050000     0.6      0.2  0.050000     0.2   
6  7.200000      1.2       2.3  3.550000     0.8      0.3  0.600000     1.0   
7  4.500000      0.2       1.2  0.600000     1.6      0.9  1.850000     1.4   
8  2.400000      0.4       0.3  0.900000     0.8      0.0 -1.800000     2.0   
9 -1.800000     -1.8      -2.2 -1.800000     4.0      4.1  2.250000    -2.8   

   CDiff10   CDiff20  YDiff5  YDiff10   YDiff20  RDiff5  RDiff10  RDiff20  H1  \
0     -1.6 -0.550000     1.4      0.3  0.350000    -0.4      0.0     0.00   0   
1      2.3  1.050000    -0.4     -0.8 -0.450000    -0.2     -0.1    -0.15   0   
2     -0.2  0.200000     1.0      0.2  0.000000    -0.2     -0.1    -0.10   3   
3      1.2  0.945455     0.2      0.8  0.513636     0.0      0.0     0.00   3   
4      0.0 -1.600000    -1.6     -1.1 -0.400000     0.2      0.1     0.05   0   
5      1.1  0.600000     0.0     -0.1  0.700000     0.0     -0.2 

In [3]:
GW12 = GW12[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW12

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0      -0.8       -1.3  -0.550000      0.0      -0.7 -0.900000      0.2   
1       1.4        1.7   1.050000      1.6       1.3  1.200000     -1.8   
2       0.0        0.1   0.500000     -0.4      -0.2  0.200000      0.2   
3       1.4        0.9   1.304545      0.0       0.2  0.390909     -0.6   
4      -1.6       -1.2  -0.850000     -1.4      -1.4 -1.400000      2.4   
5       1.2        1.3   0.700000      2.0       1.7  0.650000     -0.2   
6       0.0        1.1   0.900000      0.4       1.1  1.450000     -0.2   
7      -0.4        0.8   0.750000     -0.2       0.6  0.900000      0.0   
8      -0.4        0.0   0.000000      0.4       0.6  0.350000      0.8   
9       0.2       -1.0  -1.450000      0.0      -0.9 -1.050000      0.2   

   GCDiff10  GCDiff20  SDiff5  SDiff10   SDiff20  STDiff5  STDiff10  STDiff20  \
0       0.7  0.000000    -4.0     -6.2 -4.500000     -0.6      -2.4 -2.200000   
1      -1.6 -0.650000     2.8      3.5  2.200000      1.2       2.0  1.700000   
2      -0.1 -0.400000    -4.8     -3.2 -1.700000     -1.8      -0.7 -0.700000   
3      -0.1 -0.809091     3.0      2.7  5.031818      2.0       2.5  3.204545   
4       1.6  0.900000    -3.6     -2.7 -4.300000     -1.8      -1.6 -1.850000   
5      -0.6 -0.400000     2.8      3.6  2.500000      1.8       2.1  1.050000   
6      -1.0 -0.350000     1.8      4.6  7.200000      1.2       2.3  3.550000   
7      -0.3  0.000000     4.4      3.9  4.500000      0.2       1.2  0.600000   
8       0.6  0.250000     1.6      0.2  2.400000      0.4       0.3  0.900000   
9       0.3  0.750000    -2.8     -2.0 -1.800000     -1.8      -2.2 -1.800000   

   FDiff5  FDiff10   FDiff20  CDiff5  CDiff10   CDiff20  YDiff5  YDiff10  \
0     3.8      2.5  2.550000     0.4     -1.6 -0.550000     1.4      0.3   
1     0.0     -1.2 -0.350000     0.0      2.3  1.050000    -0.4     -0.8   
2     0.2      0.2 -0.100000     1.2     -0.2  0.200000     1.0      0.2   
3    -0.8     -1.2 -0.804545     2.0      1.2  0.945455     0.2      0.8   
4    -0.4      1.4  0.000000     1.4      0.0 -1.600000    -1.6     -1.1   
5     0.6      0.2  0.050000     0.2      1.1  0.600000     0.0     -0.1   
6     0.8      0.3  0.600000     1.0      1.9  1.400000    -0.4     -0.1   
7     1.6      0.9  1.850000     1.4      2.2  2.100000    -1.4     -1.1   
8     0.8      0.0 -1.800000     2.0      1.1  1.400000     0.8     -0.4   
9     4.0      4.1  2.250000    -2.8     -1.5 -0.900000     1.4      1.4   

    YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0  0.350000    -0.4      0.0     0.00   0   0            0            0   
1 -0.450000    -0.2     -0.1    -0.15   0   0            0            0   
2  0.000000    -0.2     -0.1    -0.10   3   1            0            0   
3  0.513636     0.0      0.0     0.00   3   1            0            0   
4 -0.400000     0.2      0.1     0.05   0   3            0            0   
5  0.700000     0.0     -0.2    -0.10   0   0            0            0   
6  0.000000     0.0     -0.1    -0.05   1   3            0            0   
7 -0.500000     0.4      0.4     0.20   1   3            0            1   
8 -0.600000    -0.2     -0.1    -0.05   0   3            0            0   
9  1.400000    -0.2     -0.2    -0.10   3   3            0            1   

   HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  HLossStreak3  \
0            0            0             0             0             0   
1            0            0             0             1             0   
2            0            0             0             0             0   
3            0            0             0             0             0   
4            0            0             0             0             0   
5            0            0             0             0             0   
6            0            0             0             0             0   
7            0            0           

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW12_predictions = np.argmax(diff_model.predict(GW12), axis=1)
GW12_predictions

1/1 [==============================] - 1s 511ms/step


array([0, 2, 2, 2, 0, 2, 2, 2, 2, 0], dtype=int64)

In [7]:
diff_model.predict(GW12)

1/1 [==============================] - 0s 35ms/step


array([[4.50720429e-01, 2.30855808e-01, 1.87075913e-01, 1.77866849e-03,
        1.88311574e-03, 2.36948486e-03, 1.80470676e-03, 1.38918601e-03,
        2.44459906e-03, 1.78332243e-03, 2.28504604e-03, 2.12416076e-03,
        1.71506894e-03, 2.05567991e-03, 2.49258499e-03, 2.28412682e-03,
        2.25076359e-03, 1.24173611e-03, 1.36504520e-03, 1.94100966e-03,
        1.45186263e-03, 2.02237396e-03, 1.66371337e-03, 1.62699877e-03,
        1.69078517e-03, 2.63451785e-03, 1.75925880e-03, 2.21919944e-03,
        2.17070663e-03, 1.79881905e-03, 1.34489243e-03, 1.97945233e-03,
        2.33366410e-03, 1.50704151e-03, 1.47396408e-03, 1.53762207e-03,
        1.90946250e-03, 2.12073978e-03, 1.16603938e-03, 1.45903463e-03,
        1.53020315e-03, 1.67065987e-03, 1.92081905e-03, 1.25004153e-03,
        2.21164967e-03, 1.81431451e-03, 1.69554865e-03, 2.23914674e-03,
        1.82302471e-03, 1.38091401e-03, 2.38774810e-03, 1.52655493e-03,
        3.21596302e-03, 2.61792541e-03, 1.89784355e-03, 2.528351

In [8]:
GW12_predictions_2 = np.argmax(diff_model_2.predict(GW12), axis=1)
GW12_predictions_2

1/1 [==============================] - 0s 103ms/step


array([0, 2, 2, 2, 0, 2, 2, 2, 2, 0], dtype=int64)

In [9]:
diff_model_2.predict(GW12)

1/1 [==============================] - 0s 36ms/step


array([[0.50073165, 0.23508716, 0.26418123],
       [0.11736955, 0.20378989, 0.6788406 ],
       [0.24331309, 0.2502226 , 0.50646436],
       [0.10886348, 0.18355736, 0.7075791 ],
       [0.5478426 , 0.3088036 , 0.14335383],
       [0.15753712, 0.23867194, 0.6037908 ],
       [0.06660001, 0.13577276, 0.7976272 ],
       [0.11528309, 0.22042356, 0.6642933 ],
       [0.19772919, 0.25136283, 0.550908  ],
       [0.5212612 , 0.26121542, 0.21752329]], dtype=float32)

In [10]:
GW12_predictions_3 = np.argmax(diff_model_3.predict(GW12), axis=1)
GW12_predictions_3

1/1 [==============================] - 0s 102ms/step


array([0, 2, 2, 2, 0, 2, 2, 2, 2, 0], dtype=int64)

In [11]:
diff_model_3.predict(GW12)

1/1 [==============================] - 0s 32ms/step


array([[0.47699755, 0.24686974, 0.2761327 ],
       [0.09437916, 0.17515111, 0.7304698 ],
       [0.26369733, 0.27077743, 0.46552527],
       [0.11110026, 0.19086015, 0.69803965],
       [0.62150085, 0.26111925, 0.11737993],
       [0.15444154, 0.21506284, 0.6304957 ],
       [0.06375843, 0.14263667, 0.79360497],
       [0.12497507, 0.22699586, 0.6480291 ],
       [0.19325043, 0.24921006, 0.55753946],
       [0.5104157 , 0.25408697, 0.23549737]], dtype=float32)