In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW13 = pd.read_csv('GW13.csv')
GW13

HomeTeam        AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  \
0          Man City       Liverpool  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
1           Burnley        West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
2             Luton  Crystal Palace  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
3         Newcastle         Chelsea  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
4     Nott'm Forest        Brighton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
5  Sheffield United     Bournemouth  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
6         Brentford         Arsenal  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
7         Tottenham     Aston Villa  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
8           Everton      Man United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
9            Fulham          Wolves  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   

   AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.2       -0.1       0.00   
1 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.8       -0.9      -0.55   
2 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4       -0.6      -0.85   
3 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0        0.2       0.70   
4 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.2       -0.3      -0.40   
5 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4       -0.3      -0.20   
6 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.2       -0.9      -0.30   
7 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.2        0.0      -0.30   
8 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4       -0.4      -0.70   
9 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.8       -0.6      -0.15   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5  SDiff10  \
0      0.8       0.5  0.100000      0.8       0.4 -0.200000    -6.2     -1.1   
1     -1.0      -0.9 -0.800000      0.4       0.4  0.150000    -2.4     -1.0   
2     -0.2      -0.2 -0.316667     -0.2       0.0  0.583333    -1.0      1.3   
3     -1.0       0.3  0.850000     -0.8      -0.1 -0.500000    -4.2     -1.3   
4      0.0      -0.6 -0.700000      0.2      -0.4 -0.100000     0.8     -2.4   
5     -0.2       0.0 -0.350000      0.0       0.5  0.050000    -3.2     -2.1   
6     -0.4      -0.9 -0.600000      0.6       0.6 -0.050000     1.0      0.2   
7     -0.8      -0.4  0.000000      0.2       0.1  0.650000    -4.2      0.6   
8      0.4       0.2  0.000000      0.0      -0.2  0.450000    -2.0     -0.2   
9     -0.6      -0.6  0.000000      0.2       0.2 -0.200000     0.2      0.8   

    SDiff20  STDiff5  STDiff10  STDiff20  FDiff5  FDiff10   FDiff20  CDiff5  \
0 -2.050000      0.2       1.7  1.100000    -4.8     -3.7 -3.600000    -0.2   
1 -0.800000      0.0      -0.5 -0.700000    -0.6      0.1  0.850000     1.0   
2 -0.683333      0.2      -1.1 -1.283333    -0.8      0.0  0.116667    -2.8   
3  1.500000     -1.4       0.4  1.050000    -0.4     -1.2  0.500000    -0.8   
4 -5.950000      0.2      -1.5 -2.500000     0.4     -0.5 -1.100000    -1.6   
5 -2.300000     -2.8      -1.3 -1.700000     1.2     -1.1  0.150000    -2.0   
6 -1.000000      1.0      -1.2 -0.700000     2.8      1.4  0.250000    -1.8   
7  1.400000     -1.8       0.0  0.850000     2.6      1.5  0.600000    -4.2   
8 -2.650000     -0.8      -0.2 -0.550000     2.8      1.9  1.150000    -2.6   
9 -0.750000     -0.2       0.4  0.000000    -3.0     -3.3 -2.750000    -1.8   

   CDiff10  CDiff20  YDiff5  YDiff10   YDiff20  RDiff5  RDiff10  RDiff20  H1  \
0      0.6    -0.90     0.4      0.4 -0.250000     0.2     -0.1    -0.10   1   
1      0.9     0.75    -1.2     -0.3  0.000000     0.2      0.2     0.15   0   
2      0.1    -0.25    -0.8     -0.5 -0.033333     0.0      0.0     0.00   0   
3     -0.4     1.25    -0.6     -1.0 -0.550000     0.0      0.0     0.00   0   
4     -2.3    -2.00     0.4      0.6 -0.200000    -0.2      0.1     0.05   0   
5     -1.6    -0.70     0.6      0.9  0.650000    -0.2      0.0     0.00 

In [3]:
GW13 = GW13[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW13

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0      -0.2       -0.1       0.00      0.8       0.5  0.100000      0.8   
1      -0.8       -0.9      -0.55     -1.0      -0.9 -0.800000      0.4   
2      -0.4       -0.6      -0.85     -0.2      -0.2 -0.316667     -0.2   
3       0.0        0.2       0.70     -1.0       0.3  0.850000     -0.8   
4       0.2       -0.3      -0.40      0.0      -0.6 -0.700000      0.2   
5      -0.4       -0.3      -0.20     -0.2       0.0 -0.350000      0.0   
6      -0.2       -0.9      -0.30     -0.4      -0.9 -0.600000      0.6   
7      -0.2        0.0      -0.30     -0.8      -0.4  0.000000      0.2   
8      -0.4       -0.4      -0.70      0.4       0.2  0.000000      0.0   
9      -0.8       -0.6      -0.15     -0.6      -0.6  0.000000      0.2   

   GCDiff10  GCDiff20  SDiff5  SDiff10   SDiff20  STDiff5  STDiff10  STDiff20  \
0       0.4 -0.200000    -6.2     -1.1 -2.050000      0.2       1.7  1.100000   
1       0.4  0.150000    -2.4     -1.0 -0.800000      0.0      -0.5 -0.700000   
2       0.0  0.583333    -1.0      1.3 -0.683333      0.2      -1.1 -1.283333   
3      -0.1 -0.500000    -4.2     -1.3  1.500000     -1.4       0.4  1.050000   
4      -0.4 -0.100000     0.8     -2.4 -5.950000      0.2      -1.5 -2.500000   
5       0.5  0.050000    -3.2     -2.1 -2.300000     -2.8      -1.3 -1.700000   
6       0.6 -0.050000     1.0      0.2 -1.000000      1.0      -1.2 -0.700000   
7       0.1  0.650000    -4.2      0.6  1.400000     -1.8       0.0  0.850000   
8      -0.2  0.450000    -2.0     -0.2 -2.650000     -0.8      -0.2 -0.550000   
9       0.2 -0.200000     0.2      0.8 -0.750000     -0.2       0.4  0.000000   

   FDiff5  FDiff10   FDiff20  CDiff5  CDiff10  CDiff20  YDiff5  YDiff10  \
0    -4.8     -3.7 -3.600000    -0.2      0.6    -0.90     0.4      0.4   
1    -0.6      0.1  0.850000     1.0      0.9     0.75    -1.2     -0.3   
2    -0.8      0.0  0.116667    -2.8      0.1    -0.25    -0.8     -0.5   
3    -0.4     -1.2  0.500000    -0.8     -0.4     1.25    -0.6     -1.0   
4     0.4     -0.5 -1.100000    -1.6     -2.3    -2.00     0.4      0.6   
5     1.2     -1.1  0.150000    -2.0     -1.6    -0.70     0.6      0.9   
6     2.8      1.4  0.250000    -1.8     -2.9    -2.30     2.2      1.4   
7     2.6      1.5  0.600000    -4.2     -0.9    -0.70     0.0      0.8   
8     2.8      1.9  1.150000    -2.6     -2.9    -1.55     0.8     -0.2   
9    -3.0     -3.3 -2.750000    -1.8      0.8     0.15    -0.4     -0.5   

    YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0 -0.250000     0.2     -0.1    -0.10   1   3            0            0   
1  0.000000     0.2      0.2     0.15   0   3            0            0   
2 -0.033333     0.0      0.0     0.00   0   0            0            0   
3 -0.550000     0.0      0.0     0.00   0   1            0            0   
4 -0.200000    -0.2      0.1     0.05   0   1            0            0   
5  0.650000    -0.2      0.0     0.00   1   3            0            0   
6  1.050000    -0.2     -0.1    -0.10   0   3            0            0   
7 -0.050000     0.6      0.3     0.15   0   3            0            0   
8 -0.150000     0.2      0.1     0.10   3   3            0            0   
9 -0.900000    -0.2     -0.1    -0.05   0   3            0            0   

   HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  HLossStreak3  \
0            0            0             0             0             0   
1            0            0             1             0             1   
2            0            0             0             0             0   
3            0            0             0             0             0   
4            0            0             0             0             0   
5            0            0             0             0             0   
6            0            0             0             0             0   
7            0            0             0        

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW13_predictions = np.argmax(diff_model.predict(GW13), axis=1)
GW13_predictions

1/1 [==============================] - 1s 532ms/step


array([2, 0, 0, 2, 0, 0, 0, 2, 0, 2], dtype=int64)

In [7]:
diff_model.predict(GW13)

1/1 [==============================] - 0s 36ms/step


array([[2.95363188e-01, 2.69069195e-01, 4.34406251e-01, 1.02227905e-05,
        1.31235556e-05, 1.49024963e-05, 1.81923679e-05, 1.91990712e-05,
        1.80260049e-05, 1.50605438e-05, 2.57218635e-05, 1.32537089e-05,
        2.37560998e-05, 1.17107666e-05, 1.64094508e-05, 2.01204530e-05,
        2.68038057e-05, 1.43953557e-05, 1.15753355e-05, 1.63249297e-05,
        8.10887923e-06, 2.27020628e-05, 2.02004558e-05, 1.94298300e-05,
        1.64528101e-05, 1.32072510e-05, 1.67399794e-05, 1.89528237e-05,
        1.17883401e-05, 1.13590295e-05, 1.09344919e-05, 1.48380004e-05,
        2.77859053e-05, 7.22865070e-06, 2.01089424e-05, 1.72294604e-05,
        1.18075914e-05, 3.06842412e-05, 1.66240807e-05, 1.70417461e-05,
        9.86849045e-06, 1.41747169e-05, 1.06314183e-05, 9.93409776e-06,
        1.48655481e-05, 1.41203036e-05, 1.85063691e-05, 8.90937827e-06,
        2.36305787e-05, 1.91409345e-05, 2.27209293e-05, 1.02607555e-05,
        1.40749553e-05, 2.79775941e-05, 1.24567996e-05, 2.581111

In [8]:
GW13_predictions_2 = np.argmax(diff_model_2.predict(GW13), axis=1)
GW13_predictions_2

1/1 [==============================] - 0s 107ms/step


array([2, 2, 2, 2, 0, 0, 0, 2, 0, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW13)

1/1 [==============================] - 0s 33ms/step


array([[0.32752898, 0.2668978 , 0.4055731 ],
       [0.3325912 , 0.2703828 , 0.39702594],
       [0.35963598, 0.27039108, 0.36997297],
       [0.14893332, 0.18243746, 0.6686291 ],
       [0.49678108, 0.28512084, 0.2180981 ],
       [0.4093559 , 0.2817274 , 0.30891663],
       [0.46307442, 0.2501421 , 0.28678343],
       [0.32911322, 0.26488227, 0.40600443],
       [0.41442668, 0.25863752, 0.3269358 ],
       [0.30204237, 0.27544945, 0.4225082 ]], dtype=float32)

In [10]:
GW13_predictions_3 = np.argmax(diff_model_3.predict(GW13), axis=1)
GW13_predictions_3

1/1 [==============================] - 0s 124ms/step


array([2, 0, 0, 2, 0, 0, 0, 2, 0, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW13)

1/1 [==============================] - 0s 33ms/step


array([[0.31846508, 0.25181022, 0.42972466],
       [0.36690584, 0.27098346, 0.3621108 ],
       [0.38658932, 0.2773765 , 0.33603418],
       [0.16750108, 0.21633482, 0.61616415],
       [0.4932966 , 0.26429048, 0.24241291],
       [0.3968555 , 0.2598049 , 0.34333953],
       [0.45383707, 0.25010714, 0.29605588],
       [0.33481926, 0.26141146, 0.4037692 ],
       [0.40565225, 0.26467943, 0.32966828],
       [0.28745514, 0.2746643 , 0.43788058]], dtype=float32)