In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW14 = pd.read_csv('GW14.csv')
GW14

HomeTeam          AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  AF  \
0        Arsenal            Wolves  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
1      Brentford             Luton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
2        Burnley  Sheffield United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
3  Nott'm Forest           Everton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
4      Newcastle        Man United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
5    Bournemouth       Aston Villa  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
6        Chelsea          Brighton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
7      Liverpool            Fulham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
8       West Ham    Crystal Palace  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
9       Man City         Tottenham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   

   HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6        1.1   0.900000   
1 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.8        0.2   0.907692   
2 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.8       -0.1   0.000000   
3 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.6       -0.4   0.050000   
4 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4        0.2  -0.200000   
5 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.6       -1.1  -1.050000   
6 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.2       -0.4  -0.550000   
7 NaN NaN NaN NaN NaN NaN   NaN   NaN       1.4        1.0   1.150000   
8 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6        0.2   0.100000   
9 NaN NaN NaN NaN NaN NaN   NaN   NaN       1.0        0.1   0.600000   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5  SDiff10  \
0      0.4       0.6  0.900000     -1.0      -1.1 -0.850000     0.6      3.6   
1      0.4       0.3  0.576923     -0.4       0.1 -0.669231     5.0      3.2   
2     -0.4      -0.2  0.200000      0.0      -0.8 -0.100000     0.8      0.8   
3      0.6      -0.3  0.300000      0.6       0.1  0.100000     0.6     -3.4   
4      0.8       1.3  0.950000      0.2      -0.2  0.100000    -0.6     -0.8   
5     -0.6      -1.1 -0.900000      0.8       1.0  0.800000    -1.0     -2.6   
6      0.8      -0.2 -0.450000      1.2      -0.2 -0.100000     3.4      1.9   
7      1.0       1.2  1.000000     -1.4      -0.9 -0.650000     7.4      5.9   
8      0.4       0.5  0.500000      0.0       0.4  0.500000     0.4      0.8   
9      1.8       0.8  0.350000     -0.4      -0.3 -0.900000     5.2     -0.4   

    SDiff20  STDiff5  STDiff10  STDiff20  FDiff5  FDiff10   FDiff20  CDiff5  \
0  3.350000     -0.8       0.8  1.900000    -3.6     -4.6 -3.800000    -0.4   
1  1.715385      1.6       1.4  1.907692     0.0     -1.2 -1.292308     0.4   
2  2.300000      1.6       0.6  1.400000    -1.4     -1.5 -1.000000     2.4   
3 -4.000000      0.6      -0.7 -1.300000    -1.6     -0.7 -0.300000    -0.2   
4 -1.300000      0.6       1.1  0.450000     0.4      1.3  0.800000    -1.8   
5 -1.650000      1.0      -0.5 -0.400000     1.0      1.7  1.150000    -0.4   
6 -1.300000      1.0       0.2 -0.750000     4.6      1.4 -1.000000     0.2   
7  6.850000      2.2       1.6  1.800000    -0.6      0.6  1.200000     2.8   
8 -1.150000     -0.8      -0.3 -0.300000    -2.4     -0.8 -1.600000    -1.2   
9  1.000000      3.6       1.4  0.750000    -2.8     -2.6 -2.650000     4.0   

   CDiff10   CDiff20  YDiff5  YDiff10  YDiff20  RDiff5  RDiff10  RDiff20  H1  \
0      3.4  2.550000    -2.2     -1.5    -1.75     0.2     -0.1    -0.05   3   
1     -0.3 -0.603846     0.4      0.8     0.25     0.0      0.0     0.00   0   
2      2.5  1.900000    -1.4     -0.8    -0.70     0.2      0.1     0.15   0   
3     -0.4 -1.700000    -0.4      0.7     0.40    -0.2      0.0     0.00   0   
4     -1.8 -0.450000     1.8      1.0     0.40     0.0      0.0     0.00   3   
5     -1.1 -1.000000    -0.4     -0.9    -0.95     0.2      0.1     0.05   3   
6

In [3]:
GW14 = GW14[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW14

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0       0.6        1.1   0.900000      0.4       0.6  0.900000     -1.0   
1       0.8        0.2   0.907692      0.4       0.3  0.576923     -0.4   
2      -0.8       -0.1   0.000000     -0.4      -0.2  0.200000      0.0   
3      -0.6       -0.4   0.050000      0.6      -0.3  0.300000      0.6   
4      -0.4        0.2  -0.200000      0.8       1.3  0.950000      0.2   
5      -0.6       -1.1  -1.050000     -0.6      -1.1 -0.900000      0.8   
6      -0.2       -0.4  -0.550000      0.8      -0.2 -0.450000      1.2   
7       1.4        1.0   1.150000      1.0       1.2  1.000000     -1.4   
8       0.6        0.2   0.100000      0.4       0.5  0.500000      0.0   
9       1.0        0.1   0.600000      1.8       0.8  0.350000     -0.4   

   GCDiff10  GCDiff20  SDiff5  SDiff10   SDiff20  STDiff5  STDiff10  STDiff20  \
0      -1.1 -0.850000     0.6      3.6  3.350000     -0.8       0.8  1.900000   
1       0.1 -0.669231     5.0      3.2  1.715385      1.6       1.4  1.907692   
2      -0.8 -0.100000     0.8      0.8  2.300000      1.6       0.6  1.400000   
3       0.1  0.100000     0.6     -3.4 -4.000000      0.6      -0.7 -1.300000   
4      -0.2  0.100000    -0.6     -0.8 -1.300000      0.6       1.1  0.450000   
5       1.0  0.800000    -1.0     -2.6 -1.650000      1.0      -0.5 -0.400000   
6      -0.2 -0.100000     3.4      1.9 -1.300000      1.0       0.2 -0.750000   
7      -0.9 -0.650000     7.4      5.9  6.850000      2.2       1.6  1.800000   
8       0.4  0.500000     0.4      0.8 -1.150000     -0.8      -0.3 -0.300000   
9      -0.3 -0.900000     5.2     -0.4  1.000000      3.6       1.4  0.750000   

   FDiff5  FDiff10   FDiff20  CDiff5  CDiff10   CDiff20  YDiff5  YDiff10  \
0    -3.6     -4.6 -3.800000    -0.4      3.4  2.550000    -2.2     -1.5   
1     0.0     -1.2 -1.292308     0.4     -0.3 -0.603846     0.4      0.8   
2    -1.4     -1.5 -1.000000     2.4      2.5  1.900000    -1.4     -0.8   
3    -1.6     -0.7 -0.300000    -0.2     -0.4 -1.700000    -0.4      0.7   
4     0.4      1.3  0.800000    -1.8     -1.8 -0.450000     1.8      1.0   
5     1.0      1.7  1.150000    -0.4     -1.1 -1.000000    -0.4     -0.9   
6     4.6      1.4 -1.000000     0.2      0.4 -0.450000     1.4      1.1   
7    -0.6      0.6  1.200000     2.8      0.8  1.800000    -1.4     -0.8   
8    -2.4     -0.8 -1.600000    -1.2      0.3 -0.700000     0.4      0.3   
9    -2.8     -2.6 -2.650000     4.0      1.0  1.050000     0.0     -0.5   

   YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0    -1.75     0.2     -0.1    -0.05   3   0            0            0   
1     0.25     0.0      0.0     0.00   0   3            0            0   
2    -0.70     0.2      0.1     0.15   0   0            0            0   
3     0.40    -0.2      0.0     0.00   0   0            0            0   
4     0.40     0.0      0.0     0.00   3   3            0            1   
5    -0.95     0.2      0.1     0.05   3   3            0            0   
6     0.15    -0.2     -0.1    -0.05   0   3            0            0   
7    -0.20     0.0      0.2     0.10   1   3            0            0   
8     0.20     0.0      0.0     0.05   3   0            0            0   
9    -1.05    -0.2     -0.1    -0.05   1   0            0            0   

   HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  HLossStreak3  \
0            0            0             0             0             0   
1            0            0             0             0             0   
2            0            0             1             0             1   
3            0            0             0             0             0   
4            0            0             0             0             0   
5            0            0             0             0             0   
6            0            0             0             0             0   
7            0            0             0        

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW14_predictions = np.argmax(diff_model.predict(GW14), axis=1)
GW14_predictions

1/1 [==============================] - 0s 365ms/step


array([2, 2, 2, 0, 2, 0, 1, 2, 2, 2], dtype=int64)

In [7]:
diff_model.predict(GW14)

1/1 [==============================] - 0s 37ms/step


array([[1.12038739e-01, 1.75812781e-01, 7.06440508e-01, 5.22436276e-05,
        5.90752024e-05, 5.51527010e-05, 5.39551438e-05, 4.40872027e-05,
        1.00211044e-04, 8.34634266e-05, 9.80338082e-05, 9.29750458e-05,
        6.06491158e-05, 1.04820851e-04, 9.66757943e-05, 7.88782272e-05,
        1.62327109e-04, 1.03233557e-04, 7.02370889e-05, 1.29789260e-04,
        6.42070954e-05, 6.82608807e-05, 1.48112915e-04, 8.59778520e-05,
        8.54836180e-05, 1.75721114e-04, 5.63347530e-05, 9.08512447e-05,
        5.87313007e-05, 4.99052512e-05, 4.52004169e-05, 7.69087419e-05,
        1.02394435e-04, 5.51071680e-05, 1.13671005e-04, 9.15591809e-05,
        7.64067881e-05, 8.83699249e-05, 6.30071518e-05, 8.06194948e-05,
        4.41321754e-05, 8.43074886e-05, 8.80162479e-05, 5.61663583e-05,
        8.55264298e-05, 1.02337137e-04, 5.25013493e-05, 7.76222369e-05,
        7.55191504e-05, 1.94946420e-04, 7.44196950e-05, 6.50665679e-05,
        9.70716719e-05, 7.95983797e-05, 5.64766015e-05, 5.763209

In [8]:
GW14_predictions_2 = np.argmax(diff_model_2.predict(GW14), axis=1)
GW14_predictions_2

1/1 [==============================] - 0s 147ms/step


array([2, 2, 2, 0, 2, 0, 0, 2, 2, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW14)

1/1 [==============================] - 0s 33ms/step


array([[0.08142401, 0.18402913, 0.7345469 ],
       [0.22683716, 0.25038323, 0.5227796 ],
       [0.14844418, 0.20785627, 0.64369965],
       [0.44328633, 0.2707707 , 0.2859429 ],
       [0.2800884 , 0.22583751, 0.4940741 ],
       [0.45319426, 0.25373557, 0.29307014],
       [0.36141297, 0.31763712, 0.32094988],
       [0.06818544, 0.1549764 , 0.77683824],
       [0.30318898, 0.2992144 , 0.39759657],
       [0.15826893, 0.22363523, 0.6180959 ]], dtype=float32)

In [10]:
GW14_predictions_3 = np.argmax(diff_model_3.predict(GW14), axis=1)
GW14_predictions_3

1/1 [==============================] - 0s 101ms/step


array([2, 2, 2, 2, 2, 0, 2, 2, 2, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW14)

1/1 [==============================] - 0s 55ms/step


array([[0.08433202, 0.2066142 , 0.7090539 ],
       [0.19180575, 0.22215028, 0.5860439 ],
       [0.15358584, 0.23262762, 0.6137865 ],
       [0.35400423, 0.25984597, 0.38614976],
       [0.21419938, 0.22242084, 0.5633799 ],
       [0.4777626 , 0.26783016, 0.25440723],
       [0.33943772, 0.28785482, 0.37270746],
       [0.08075114, 0.15624706, 0.76300186],
       [0.30274945, 0.29213524, 0.40511534],
       [0.13409609, 0.20296858, 0.6629353 ]], dtype=float32)