In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW15 = pd.read_csv('GW15.csv')
GW15

HomeTeam       AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  AF  \
0            Wolves        Burnley  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
1             Luton        Arsenal  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
2          Brighton      Brentford  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
3    Crystal Palace    Bournemouth  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
4            Fulham  Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
5  Sheffield United      Liverpool  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
6       Aston Villa       Man City  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
7        Man United        Chelsea  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
8           Everton      Newcastle  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
9         Tottenham       West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   

   HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.2        0.6   0.400000   
1 NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.6       -1.4  -1.457143   
2 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.6        0.0  -0.250000   
3 NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.2       -0.2   0.250000   
4 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.2        0.4  -0.100000   
5 NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.4       -1.7  -1.550000   
6 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.2        0.5  -0.200000   
7 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.4        0.3   0.600000   
8 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0       -0.7  -0.500000   
9 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.6        0.6   0.350000   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5  SDiff10  \
0      0.0       0.4  0.100000      0.2      -0.3 -0.050000    -1.4     -1.2   
1     -1.2      -1.0 -1.071429      1.2       0.9  0.857143    -7.4     -3.1   
2      0.0       0.4  0.400000      0.2       0.6  0.850000    -2.0     -3.2   
3     -0.6      -0.3  0.050000     -0.4      -0.7 -0.500000    -4.0     -2.5   
4      0.4       0.2 -0.050000      0.2       0.0  0.250000     0.6      0.1   
5     -1.6      -1.6 -1.600000      2.0       2.1  1.200000   -11.6     -9.9   
6     -1.4       0.0 -0.350000     -0.4      -0.3  0.300000    -4.6     -1.3   
7     -1.4      -0.9 -0.400000     -1.8      -0.7 -0.650000    -3.0      0.9   
8     -0.4      -1.2 -0.850000      0.2       0.5  0.500000    -0.4      0.7   
9      0.0       0.2  0.400000      0.8      -0.4 -0.200000    -2.0      2.9   

    SDiff20  STDiff5  STDiff10  STDiff20  FDiff5  FDiff10   FDiff20  CDiff5  \
0 -0.850000     -0.6      -0.1 -0.500000     3.0      3.9  2.850000    -1.0   
1 -2.978571     -2.2      -1.9 -2.678571     1.6      1.7  1.378571    -2.4   
2  0.750000      1.6       0.7  1.250000    -0.2      0.2  1.900000     1.4   
3  0.750000     -3.0      -1.9 -0.200000     1.4     -2.0 -1.000000    -0.4   
4  0.300000      1.6       0.6  0.300000    -0.8     -0.9 -1.000000     1.4   
5 -8.650000     -6.2      -4.2 -3.300000     1.0      0.0 -0.850000    -3.4   
6 -2.600000     -2.8      -1.6 -1.350000    -0.2      1.6  1.900000    -3.6   
7  2.350000     -2.2      -1.0  0.050000    -5.2     -3.2 -1.100000     0.8   
8 -0.750000      0.0      -1.4 -0.750000     3.2      2.3  0.300000    -1.2   
9  2.900000      0.8       1.3  1.700000     1.8      1.7  1.000000     0.0   

   CDiff10   CDiff20  YDiff5  YDiff10  YDiff20  RDiff5  RDiff10  RDiff20  H1  \
0     -1.6 -1.200000     1.0      1.1     1.05     0.0      0.1    -0.05   0   
1     -2.2 -1.907143     2.0      0.7     0.85    -0.2     -0.1    -0.10   0   
2      0.0  0.850000     1.0     -0.2     0.55     0.4      0.2     0.10   0   
3     -0.3  0.750000    -0.4      0.1    -0.20     0.0     -0.1    -0.05   1   
4      1.4  1.550000     1.2     -0.2    -0.40     0.0     -0.1     0.00   0   
5     -2.9 -2.800000     1.8      1.3     0.85     0.2      0.0    -0.10   0   
6   

In [3]:
GW15 = GW15[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW15

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0       0.2        0.6   0.400000      0.0       0.4  0.100000      0.2   
1      -1.6       -1.4  -1.457143     -1.2      -1.0 -1.071429      1.2   
2      -0.6        0.0  -0.250000      0.0       0.4  0.400000      0.2   
3      -1.2       -0.2   0.250000     -0.6      -0.3  0.050000     -0.4   
4       0.2        0.4  -0.100000      0.4       0.2 -0.050000      0.2   
5      -1.4       -1.7  -1.550000     -1.6      -1.6 -1.600000      2.0   
6       0.2        0.5  -0.200000     -1.4       0.0 -0.350000     -0.4   
7       0.4        0.3   0.600000     -1.4      -0.9 -0.400000     -1.8   
8       0.0       -0.7  -0.500000     -0.4      -1.2 -0.850000      0.2   
9      -0.6        0.6   0.350000      0.0       0.2  0.400000      0.8   

   GCDiff10  GCDiff20  SDiff5  SDiff10   SDiff20  STDiff5  STDiff10  STDiff20  \
0      -0.3 -0.050000    -1.4     -1.2 -0.850000     -0.6      -0.1 -0.500000   
1       0.9  0.857143    -7.4     -3.1 -2.978571     -2.2      -1.9 -2.678571   
2       0.6  0.850000    -2.0     -3.2  0.750000      1.6       0.7  1.250000   
3      -0.7 -0.500000    -4.0     -2.5  0.750000     -3.0      -1.9 -0.200000   
4       0.0  0.250000     0.6      0.1  0.300000      1.6       0.6  0.300000   
5       2.1  1.200000   -11.6     -9.9 -8.650000     -6.2      -4.2 -3.300000   
6      -0.3  0.300000    -4.6     -1.3 -2.600000     -2.8      -1.6 -1.350000   
7      -0.7 -0.650000    -3.0      0.9  2.350000     -2.2      -1.0  0.050000   
8       0.5  0.500000    -0.4      0.7 -0.750000      0.0      -1.4 -0.750000   
9      -0.4 -0.200000    -2.0      2.9  2.900000      0.8       1.3  1.700000   

   FDiff5  FDiff10   FDiff20  CDiff5  CDiff10   CDiff20  YDiff5  YDiff10  \
0     3.0      3.9  2.850000    -1.0     -1.6 -1.200000     1.0      1.1   
1     1.6      1.7  1.378571    -2.4     -2.2 -1.907143     2.0      0.7   
2    -0.2      0.2  1.900000     1.4      0.0  0.850000     1.0     -0.2   
3     1.4     -2.0 -1.000000    -0.4     -0.3  0.750000    -0.4      0.1   
4    -0.8     -0.9 -1.000000     1.4      1.4  1.550000     1.2     -0.2   
5     1.0      0.0 -0.850000    -3.4     -2.9 -2.800000     1.8      1.3   
6    -0.2      1.6  1.900000    -3.6     -1.3 -0.700000     0.8      0.4   
7    -5.2     -3.2 -1.100000     0.8      2.0  1.550000    -2.0     -2.0   
8     3.2      2.3  0.300000    -1.2     -1.3 -0.400000    -0.6     -0.7   
9     1.8      1.7  1.000000     0.0      1.4  0.600000    -1.2      0.2   

   YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0     1.05     0.0      0.1    -0.05   0   3            0            0   
1     0.85    -0.2     -0.1    -0.10   0   3            0            1   
2     0.55     0.4      0.2     0.10   0   3            0            0   
3    -0.20     0.0     -0.1    -0.05   1   1            0            0   
4    -0.40     0.0     -0.1     0.00   0   0            0            0   
5     0.85     0.2      0.0    -0.10   0   3            0            0   
6     1.30     0.0     -0.2    -0.10   1   1            0            0   
7    -0.95    -0.4     -0.2    -0.10   0   3            0            0   
8    -0.50     0.0      0.1     0.05   3   3            0            0   
9     0.40     0.4      0.3     0.10   1   1            0            0   

   HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  HLossStreak3  \
0            0            0             0             0             0   
1            0            0             0             0             0   
2            0            0             0             0             0   
3            0            0             0             0             0   
4            0            0             0             1             0   
5            0            0             0             0             0   
6            0            0             0             0             0   
7            0            0             0        

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW15_predictions = np.argmax(diff_model.predict(GW15), axis=1)
GW15_predictions

1/1 [==============================] - 0s 482ms/step


array([2, 0, 2, 2, 2, 0, 2, 2, 0, 2], dtype=int64)

In [7]:
diff_model.predict(GW15)

1/1 [==============================] - 0s 23ms/step


array([[2.92714775e-01, 2.78096884e-01, 4.22089726e-01, 1.20364239e-04,
        7.63534917e-05, 7.92735591e-05, 8.13824154e-05, 1.30233908e-04,
        1.59858522e-04, 6.36485420e-05, 1.07320862e-04, 1.19784803e-04,
        1.36854389e-04, 7.33275228e-05, 7.64235665e-05, 8.61282169e-05,
        2.16919623e-04, 6.98223666e-05, 1.10026645e-04, 1.38413583e-04,
        8.44438255e-05, 1.45740909e-04, 9.70000619e-05, 9.42330007e-05,
        1.22725687e-04, 8.77769562e-05, 7.08713342e-05, 5.37527012e-05,
        9.39015299e-05, 6.42128653e-05, 7.64285287e-05, 1.10825946e-04,
        1.24324608e-04, 6.38453348e-05, 2.06399534e-04, 1.10039975e-04,
        8.75726109e-05, 1.43261685e-04, 6.17972109e-05, 7.98175533e-05,
        7.94968946e-05, 8.42561494e-05, 8.14080340e-05, 8.19371344e-05,
        9.00433079e-05, 8.50402503e-05, 8.99443476e-05, 8.25574898e-05,
        1.19719931e-04, 1.11338144e-04, 1.36345421e-04, 4.75836205e-05,
        9.21324754e-05, 1.18930642e-04, 7.53802233e-05, 1.069168

In [8]:
GW15_predictions_2 = np.argmax(diff_model_2.predict(GW15), axis=1)
GW15_predictions_2

1/1 [==============================] - 0s 67ms/step


array([2, 0, 2, 2, 2, 0, 2, 2, 0, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW15)

1/1 [==============================] - 0s 23ms/step


array([[0.31372806, 0.26458406, 0.4216878 ],
       [0.5735762 , 0.23948468, 0.18693912],
       [0.24759117, 0.21726573, 0.535143  ],
       [0.22398755, 0.23242436, 0.5435881 ],
       [0.21786281, 0.26766258, 0.5144745 ],
       [0.7336124 , 0.2076251 , 0.05876252],
       [0.34743503, 0.28110605, 0.37145886],
       [0.15561397, 0.22452286, 0.6198632 ],
       [0.40767908, 0.28268752, 0.30963334],
       [0.1806506 , 0.22933324, 0.5900162 ]], dtype=float32)

In [10]:
GW15_predictions_3 = np.argmax(diff_model_3.predict(GW15), axis=1)
GW15_predictions_3

1/1 [==============================] - 0s 68ms/step


array([2, 0, 2, 2, 2, 0, 0, 2, 0, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW15)

1/1 [==============================] - 0s 40ms/step


array([[0.31098408, 0.23996575, 0.4490501 ],
       [0.6130983 , 0.23192932, 0.15497236],
       [0.2623495 , 0.21627758, 0.5213729 ],
       [0.20415325, 0.24014148, 0.55570525],
       [0.23696795, 0.26468468, 0.49834725],
       [0.7584659 , 0.1794391 , 0.06209498],
       [0.41416126, 0.27134925, 0.3144894 ],
       [0.23552522, 0.24981834, 0.5146564 ],
       [0.43749705, 0.28758946, 0.27491346],
       [0.17642392, 0.24065888, 0.5829172 ]], dtype=float32)