In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW16 = pd.read_csv('GW16.csv')
GW16

HomeTeam       AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  AF  \
0    Crystal Palace      Liverpool  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
1          Brighton        Burnley  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
2        Man United    Bournemouth  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
3  Sheffield United      Brentford  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
4            Wolves  Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
5       Aston Villa        Arsenal  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
6           Everton        Chelsea  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
7            Fulham       West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
8             Luton       Man City  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
9         Tottenham      Newcastle  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   

   HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.4       -1.2      -1.05   
1 NaN NaN NaN NaN NaN NaN   NaN   NaN       1.0        0.7       1.05   
2 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.4        0.8       1.00   
3 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4       -0.9      -1.00   
4 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6        0.9       0.05   
5 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4        0.0      -0.30   
6 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6        0.5       0.20   
7 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.8       -0.3      -0.25   
8 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4       -0.7      -1.40   
9 NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.6       -0.6       0.05   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5  SDiff10  \
0     -1.0      -1.4 -1.050000      0.6       0.4      0.45    -6.4     -7.4   
1      0.4       0.6  1.050000      0.0       0.0     -0.30    -0.4      1.5   
2     -0.6      -0.2  0.200000     -1.4      -1.4     -0.85    -0.2      2.0   
3     -0.6      -0.9 -0.900000      0.6       1.7      1.20    -6.8     -6.1   
4      0.2       0.6 -0.150000     -0.8      -0.6      0.20     0.0     -1.5   
5     -0.4      -0.1 -0.200000      0.0       0.0      0.30    -2.8      0.4   
6     -1.0      -0.5 -0.300000     -1.4      -0.8     -0.30     2.6      3.7   
7      0.4       0.0  0.000000      0.4      -0.2      0.05     0.6      0.1   
8     -1.4      -0.9 -1.083333      0.0       0.5      1.00    -6.6     -3.9   
9      0.2      -0.8  0.000000      1.4       0.7      0.45    -0.6     -0.1   

    SDiff20  STDiff5  STDiff10  STDiff20  FDiff5  FDiff10  FDiff20  CDiff5  \
0 -4.950000     -3.8      -3.5 -1.750000    -0.8     -1.5    -1.30    -2.6   
1  3.400000      0.8       1.1  2.250000    -1.2      0.6     1.10    -1.0   
2  4.850000     -2.0      -0.5  0.750000    -0.6     -1.9    -1.85     1.0   
3 -5.450000     -1.8      -2.3 -2.350000     1.6      0.7     1.35    -1.8   
4  0.400000      0.8       0.6  0.100000     1.6      2.5     1.65     1.6   
5 -1.000000     -0.4       0.4 -0.600000     2.0      1.6     1.20    -1.2   
6  1.050000     -1.2      -0.2 -0.100000    -1.0      0.1     0.55    -0.2   
7 -0.600000      1.2       0.6  0.000000    -1.2      0.2     0.60     0.8   
8 -4.566667     -2.4      -2.9 -3.233333    -0.8      2.0     2.65    -3.0   
9  0.100000      1.4      -0.8  0.200000     3.6      2.1    -0.20     2.2   

   CDiff10  CDiff20  YDiff5  YDiff10  YDiff20  RDiff5  RDiff10  RDiff20  H1  \
0     -1.7    -1.85     0.0      0.1    -0.30     0.0     -0.2    -0.20   0   
1     -0.7    -0.80     1.8      0.7     0.95     0.4      0.1    -0.10   3   
2      0.8     1.85    -0.8     -0.3     0.10     0.0     -0.1    -0.05   3   
3     -1.6    -0.85     1.8      0.3     0.50     0.2      0.1     0.10   0   
4      1.0     0.95     1.2      0.7     0.45     0.0      0.1     0.05   3   
5     -0.5    -1.55     1.6      1.1     1.45    -0.2     -0.1    -0.10   3   
6      0.0     0.25   

In [3]:
GW16 = GW16[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW16

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0      -1.4       -1.2      -1.05     -1.0      -1.4 -1.050000      0.6   
1       1.0        0.7       1.05      0.4       0.6  1.050000      0.0   
2       0.4        0.8       1.00     -0.6      -0.2  0.200000     -1.4   
3      -0.4       -0.9      -1.00     -0.6      -0.9 -0.900000      0.6   
4       0.6        0.9       0.05      0.2       0.6 -0.150000     -0.8   
5      -0.4        0.0      -0.30     -0.4      -0.1 -0.200000      0.0   
6       0.6        0.5       0.20     -1.0      -0.5 -0.300000     -1.4   
7      -0.8       -0.3      -0.25      0.4       0.0  0.000000      0.4   
8      -0.4       -0.7      -1.40     -1.4      -0.9 -1.083333      0.0   
9      -1.6       -0.6       0.05      0.2      -0.8  0.000000      1.4   

   GCDiff10  GCDiff20  SDiff5  SDiff10   SDiff20  STDiff5  STDiff10  STDiff20  \
0       0.4      0.45    -6.4     -7.4 -4.950000     -3.8      -3.5 -1.750000   
1       0.0     -0.30    -0.4      1.5  3.400000      0.8       1.1  2.250000   
2      -1.4     -0.85    -0.2      2.0  4.850000     -2.0      -0.5  0.750000   
3       1.7      1.20    -6.8     -6.1 -5.450000     -1.8      -2.3 -2.350000   
4      -0.6      0.20     0.0     -1.5  0.400000      0.8       0.6  0.100000   
5       0.0      0.30    -2.8      0.4 -1.000000     -0.4       0.4 -0.600000   
6      -0.8     -0.30     2.6      3.7  1.050000     -1.2      -0.2 -0.100000   
7      -0.2      0.05     0.6      0.1 -0.600000      1.2       0.6  0.000000   
8       0.5      1.00    -6.6     -3.9 -4.566667     -2.4      -2.9 -3.233333   
9       0.7      0.45    -0.6     -0.1  0.100000      1.4      -0.8  0.200000   

   FDiff5  FDiff10  FDiff20  CDiff5  CDiff10  CDiff20  YDiff5  YDiff10  \
0    -0.8     -1.5    -1.30    -2.6     -1.7    -1.85     0.0      0.1   
1    -1.2      0.6     1.10    -1.0     -0.7    -0.80     1.8      0.7   
2    -0.6     -1.9    -1.85     1.0      0.8     1.85    -0.8     -0.3   
3     1.6      0.7     1.35    -1.8     -1.6    -0.85     1.8      0.3   
4     1.6      2.5     1.65     1.6      1.0     0.95     1.2      0.7   
5     2.0      1.6     1.20    -1.2     -0.5    -1.55     1.6      1.1   
6    -1.0      0.1     0.55    -0.2      0.0     0.25    -0.6     -1.2   
7    -1.2      0.2     0.60     0.8      0.5     0.30    -0.4     -0.6   
8    -0.8      2.0     2.65    -3.0     -2.1    -1.25     0.6     -0.1   
9     3.6      2.1    -0.20     2.2      1.2     0.50     0.0      0.3   

   YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0    -0.30     0.0     -0.2    -0.20   0   3            0            0   
1     0.95     0.4      0.1    -0.10   3   0            0            0   
2     0.10     0.0     -0.1    -0.05   3   3            0            0   
3     0.50     0.2      0.1     0.10   0   0            0            0   
4     0.45     0.0      0.1     0.05   3   0            0            0   
5     1.45    -0.2     -0.1    -0.10   3   3            0            1   
6    -0.90    -0.4     -0.1    -0.05   3   0            0            0   
7    -0.20     0.0      0.0     0.05   3   3            0            0   
8     0.55     0.0     -0.2    -0.10   0   0            0            0   
9     0.20     0.4      0.3     0.15   0   0            0            0   

   HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  HLossStreak3  \
0            0            0             0             0             0   
1            0            0             0             0             0   
2            0            0             0             0             0   
3            0            0             1             0             1   
4            0            0             0             1             0   
5            0            0             0             0             0   
6            0            0             0             0             0   
7            0            0             0             0             0  

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW16_predictions = np.argmax(diff_model.predict(GW16), axis=1)
GW16_predictions

1/1 [==============================] - 0s 434ms/step


array([0, 2, 2, 0, 2, 2, 2, 2, 0, 2], dtype=int64)

In [7]:
diff_model.predict(GW16)

1/1 [==============================] - 0s 33ms/step


array([[5.40112257e-01, 2.76877791e-01, 1.76599264e-01, 1.19790966e-04,
        8.48331983e-05, 9.46874788e-05, 6.47555134e-05, 1.12494359e-04,
        1.89925588e-04, 6.53457901e-05, 1.11168811e-04, 1.18178090e-04,
        1.06520114e-04, 9.84862490e-05, 7.48065067e-05, 9.73644783e-05,
        1.25020611e-04, 8.37482439e-05, 6.97383730e-05, 8.60173968e-05,
        5.45917355e-05, 1.09354842e-04, 8.40693756e-05, 8.62539746e-05,
        9.75979128e-05, 1.12966532e-04, 7.44079953e-05, 8.90874144e-05,
        9.46951477e-05, 4.98033260e-05, 8.04210867e-05, 1.01616126e-04,
        1.87815676e-04, 4.69218685e-05, 1.52992157e-04, 1.24803322e-04,
        7.36343136e-05, 1.12557456e-04, 7.33749475e-05, 8.86516209e-05,
        7.11192697e-05, 7.55217552e-05, 7.23893681e-05, 6.65581538e-05,
        8.80496009e-05, 7.47782033e-05, 8.69022988e-05, 6.91786408e-05,
        9.93327485e-05, 1.16095092e-04, 1.17772608e-04, 5.33324092e-05,
        7.12486581e-05, 1.08004984e-04, 5.13680388e-05, 8.759189

In [8]:
GW16_predictions_2 = np.argmax(diff_model_2.predict(GW16), axis=1)
GW16_predictions_2

1/1 [==============================] - 0s 104ms/step


array([0, 2, 2, 0, 2, 0, 2, 2, 0, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW16)

1/1 [==============================] - 0s 33ms/step


array([[0.57843757, 0.24677117, 0.17479125],
       [0.14794858, 0.18288691, 0.66916454],
       [0.09384114, 0.19114178, 0.715017  ],
       [0.5892315 , 0.23768315, 0.1730854 ],
       [0.20160346, 0.24846277, 0.54993385],
       [0.38841605, 0.26501772, 0.34656626],
       [0.21034655, 0.26266068, 0.52699274],
       [0.264405  , 0.2524328 , 0.48316213],
       [0.5358751 , 0.25032932, 0.21379559],
       [0.33837894, 0.27959746, 0.38202357]], dtype=float32)

In [10]:
GW16_predictions_3 = np.argmax(diff_model_3.predict(GW16), axis=1)
GW16_predictions_3

1/1 [==============================] - 0s 134ms/step


array([0, 2, 2, 0, 2, 0, 2, 2, 0, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW16)

1/1 [==============================] - 0s 40ms/step


array([[0.55734754, 0.23965797, 0.20299453],
       [0.1600602 , 0.21133518, 0.62860465],
       [0.1154579 , 0.20444608, 0.68009603],
       [0.6095985 , 0.2363793 , 0.15402216],
       [0.20415907, 0.24025048, 0.55559045],
       [0.37866238, 0.26642787, 0.35490966],
       [0.27535337, 0.29839078, 0.42625585],
       [0.25933537, 0.25670874, 0.4839558 ],
       [0.6249888 , 0.22956033, 0.14545093],
       [0.29903406, 0.28968534, 0.41128063]], dtype=float32)