In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW1 = pd.read_csv('GW1.csv')
GW1

HomeTeam        AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  \
0           Burnley        Man City  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
1           Arsenal   Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
2       Bournemouth        West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
3          Brighton           Luton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
4           Everton          Fulham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
5  Sheffield United  Crystal Palace  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
6         Newcastle     Aston Villa  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
7         Brentford       Tottenham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
8           Chelsea       Liverpool  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
9        Man United          Wolves  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   

   AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -1.500000  -1.100000  -1.375000   
1 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.166667   0.333333   0.768182   
2 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -1.000000   0.033333  -0.100000   
3 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       NaN        NaN        NaN   
4 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -0.333333  -0.300000  -0.150000   
5 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -0.333333  -0.800000  -0.250000   
6 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -0.500000  -0.200000  -0.150000   
7 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.500000   0.500000   0.300000   
8 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -1.333333  -1.900000  -0.995455   
9 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.833333   0.800000   0.500000   

    GSDiff5  GSDiff10  GSDiff20   GCDiff5  GCDiff10  GCDiff20     SDiff5  \
0 -0.500000 -1.100000 -1.483333  1.166667  0.600000  0.541667  -2.500000   
1 -0.166667  0.700000  1.022727 -1.000000 -0.050000 -0.245455   4.666667   
2 -0.166667 -0.583333 -0.400000  0.333333 -0.066667  0.050000  -4.333333   
3       NaN       NaN       NaN       NaN       NaN       NaN        NaN   
4 -1.000000 -0.400000 -0.250000 -0.166667  0.300000  0.350000   1.000000   
5 -1.166667 -1.383333 -0.600000  0.166667  0.650000  0.550000  -3.166667   
6  0.333333  0.800000  0.250000  0.333333  0.600000  0.100000   8.166667   
7 -0.500000 -0.600000 -0.250000 -1.000000 -1.400000 -1.000000   1.000000   
8 -0.666667 -2.016667 -1.231818  1.000000  0.366667  0.127273  -2.333333   
9  1.000000  0.700000  0.450000 -1.666667 -1.100000 -0.450000  13.000000   

     SDiff10   SDiff20   STDiff5  STDiff10  STDiff20    FDiff5   FDiff10  \
0  -0.800000 -4.183333  0.666667 -1.300000 -2.541667  5.000000  1.700000   
1   4.433333  6.181818  2.666667  2.550000  1.800000 -2.833333 -1.033333   
2  -0.150000 -0.850000 -1.500000 -0.250000 -0.150000  4.333333  1.533333   
3        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4   3.000000  2.150000  0.166667  1.300000  1.050000  0.166667  0.000000   
5  -7.066667 -3.000000 -2.666667 -2.950000 -1.050000 -0.333333  0.116667   
6   5.200000  4.400000  2.000000  1.900000  1.500000  3.166667  1.600000   
7  -2.000000 -2.400000 -0.333333 -0.700000 -0.750000 -2.333333 -1.100000   
8  -4.016667 -1.618182  0.333333 -1.233333 -0.918182 -4.666667 -3.000000   
9  11.000000  6.650000  4.666667  4.400000  2.600000 -4.833333 -3.000000   

    FDiff20    CDiff5   CDiff10   CDiff20    YDiff5   YDiff10   YDiff20  \
0  1.225000 -1.000000  0.500000 -0.800000  1.166667  0.700000  0.325000   
1 -2.945455  3.000000  1.583333  2.859091 -0.833333 -0.966667 -1.195455   
2  0.950000 -2.166667 -0.983333 -1.850000  1.166667  0.966667  0.800000   
3       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4 -0.450000  2.333333 -0.800000  0.150000  0.833333  0.300000  0.000000   
5  0.100000 -1.000000 -3.033333 -1.150000  0.000000  0.400000  0.050000   
6 -0.400000  1.333333  2.300000  3.150000 -1.333333 -1.300000 -0.600000   
7 -1.900000 -1.333333 -0.50000

In [3]:
GW1 = GW1[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW1

PtsDiff5  PtsDiff10  PtsDiff20   GSDiff5  GSDiff10  GSDiff20   GCDiff5  \
0 -1.500000  -1.100000  -1.375000 -0.500000 -1.100000 -1.483333  1.166667   
1  0.166667   0.333333   0.768182 -0.166667  0.700000  1.022727 -1.000000   
2 -1.000000   0.033333  -0.100000 -0.166667 -0.583333 -0.400000  0.333333   
3       NaN        NaN        NaN       NaN       NaN       NaN       NaN   
4 -0.333333  -0.300000  -0.150000 -1.000000 -0.400000 -0.250000 -0.166667   
5 -0.333333  -0.800000  -0.250000 -1.166667 -1.383333 -0.600000  0.166667   
6 -0.500000  -0.200000  -0.150000  0.333333  0.800000  0.250000  0.333333   
7  0.500000   0.500000   0.300000 -0.500000 -0.600000 -0.250000 -1.000000   
8 -1.333333  -1.900000  -0.995455 -0.666667 -2.016667 -1.231818  1.000000   
9  0.833333   0.800000   0.500000  1.000000  0.700000  0.450000 -1.666667   

   GCDiff10  GCDiff20     SDiff5    SDiff10   SDiff20   STDiff5  STDiff10  \
0  0.600000  0.541667  -2.500000  -0.800000 -4.183333  0.666667 -1.300000   
1 -0.050000 -0.245455   4.666667   4.433333  6.181818  2.666667  2.550000   
2 -0.066667  0.050000  -4.333333  -0.150000 -0.850000 -1.500000 -0.250000   
3       NaN       NaN        NaN        NaN       NaN       NaN       NaN   
4  0.300000  0.350000   1.000000   3.000000  2.150000  0.166667  1.300000   
5  0.650000  0.550000  -3.166667  -7.066667 -3.000000 -2.666667 -2.950000   
6  0.600000  0.100000   8.166667   5.200000  4.400000  2.000000  1.900000   
7 -1.400000 -1.000000   1.000000  -2.000000 -2.400000 -0.333333 -0.700000   
8  0.366667  0.127273  -2.333333  -4.016667 -1.618182  0.333333 -1.233333   
9 -1.100000 -0.450000  13.000000  11.000000  6.650000  4.666667  4.400000   

   STDiff20    FDiff5   FDiff10   FDiff20    CDiff5   CDiff10   CDiff20  \
0 -2.541667  5.000000  1.700000  1.225000 -1.000000  0.500000 -0.800000   
1  1.800000 -2.833333 -1.033333 -2.945455  3.000000  1.583333  2.859091   
2 -0.150000  4.333333  1.533333  0.950000 -2.166667 -0.983333 -1.850000   
3       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4  1.050000  0.166667  0.000000 -0.450000  2.333333 -0.800000  0.150000   
5 -1.050000 -0.333333  0.116667  0.100000 -1.000000 -3.033333 -1.150000   
6  1.500000  3.166667  1.600000 -0.400000  1.333333  2.300000  3.150000   
7 -0.750000 -2.333333 -1.100000 -1.900000 -1.333333 -0.500000 -0.550000   
8 -0.918182 -4.666667 -3.000000 -1.822727 -2.166667 -1.416667  0.222727   
9  2.600000 -4.833333 -3.000000 -2.450000  1.666667  1.400000  1.150000   

     YDiff5   YDiff10   YDiff20    RDiff5  RDiff10  RDiff20  H1   A1  \
0  1.166667  0.700000  0.325000  0.166667      0.1    0.125   0  0.0   
1 -0.833333 -0.966667 -1.195455  0.000000      0.0    0.000   3  1.0   
2  1.166667  0.966667  0.800000  0.000000      0.0    0.000   0  0.0   
3       NaN       NaN       NaN       NaN      NaN      NaN   0  NaN   
4  0.833333  0.300000  0.000000  0.000000      0.2    0.100   3  0.0   
5  0.000000  0.400000  0.050000  0.000000      0.0    0.000   3  1.0   
6 -1.333333 -1.300000 -0.600000  0.000000      0.0    0.050   1  3.0   
7 -0.166667 -0.300000 -0.600000  0.000000     -0.1   -0.050   3  3.0   
8  0.166667  0.416667 -0.040909  0.000000      0.0    0.000   1  1.0   
9 -0.833333 -1.000000 -0.600000  0.000000      0.0   -0.050   3  0.0   

   HWinStreak3  AWinStreak3  HWinStreak5  AWinStreak5  HLossStreak3  \
0            0            0            0            0             0   
1            0            0            0            0             0   
2            0            0            0            0             1   
3            0            0            0            0             0   
4            0            0            0            0             0   
5            0            0            0            0             0   
6            0            0            0            0             0   
7            1            0            0            0             0   
8            0            0            0         

In [5]:
diff_model = load_model('first_diff_model.h5')

In [6]:
GW1_predictions = np.argmax(diff_model.predict(GW1), axis=1)
GW1_predictions

1/1 [==============================] - 0s 437ms/step


array([0, 2, 0, 0, 2, 0, 2, 2, 0, 2], dtype=int64)

In [7]:
diff_model.predict(GW1)

1/1 [==============================] - 0s 47ms/step


array([[4.99703586e-01, 2.45125949e-01, 1.42300859e-01, 1.42098998e-03,
        1.17640069e-03, 1.16397545e-03, 1.34879758e-03, 9.34387266e-04,
        1.76718272e-03, 1.28120859e-03, 1.70717784e-03, 9.38027340e-04,
        1.60688360e-03, 1.82072318e-03, 2.02239119e-03, 1.35825668e-03,
        2.42281752e-03, 1.83629955e-03, 1.74233632e-03, 2.76819454e-03,
        1.69300986e-03, 1.26418844e-03, 1.20364374e-03, 1.96678494e-03,
        1.87530881e-03, 2.41643866e-03, 2.11973372e-03, 1.88305345e-03,
        1.20316283e-03, 1.46924064e-03, 1.08127133e-03, 1.69201812e-03,
        2.12753704e-03, 1.25255925e-03, 1.17329101e-03, 1.36917084e-03,
        1.81247934e-03, 1.84954260e-03, 1.56046764e-03, 1.98175525e-03,
        9.68418899e-04, 2.01494084e-03, 1.70757517e-03, 1.26530789e-03,
        1.14652107e-03, 1.76171307e-03, 1.40990887e-03, 1.23531173e-03,
        1.78438285e-03, 1.72113196e-03, 2.15159450e-03, 1.74162199e-03,
        1.57914648e-03, 2.26283423e-03, 1.48161873e-03, 2.429001

In [8]:
diff_model_2 = load_model('second_diff_model.h5')

In [9]:
GW1_predictions_2 = np.argmax(diff_model_2.predict(GW1), axis=1)
GW1_predictions_2

1/1 [==============================] - 0s 117ms/step


array([0, 2, 0, 0, 2, 0, 2, 2, 0, 2], dtype=int64)

In [10]:
diff_model_2.predict(GW1)

1/1 [==============================] - 0s 44ms/step


array([[0.5359529 , 0.26803946, 0.19600765],
       [0.06807714, 0.15272869, 0.7791941 ],
       [0.43161267, 0.25478813, 0.3135993 ],
       [       nan,        nan,        nan],
       [0.24872105, 0.26961693, 0.48166198],
       [0.47074622, 0.25937134, 0.26988235],
       [0.14948542, 0.2602041 , 0.59031045],
       [0.2538923 , 0.242295  , 0.50381273],
       [0.43439475, 0.25261497, 0.31299028],
       [0.09616598, 0.18963662, 0.71419734]], dtype=float32)

In [11]:
weighted_diff_model = load_model('first_weighted_diff_model.h5')

In [12]:
GW1_predictions_weighted = np.argmax(weighted_diff_model.predict(GW1), axis=1)
GW1_predictions_weighted

1/1 [==============================] - 0s 142ms/step


array([0, 2, 0, 0, 2, 0, 2, 2, 0, 2], dtype=int64)

In [13]:
weighted_diff_model.predict(GW1)

1/1 [==============================] - 0s 61ms/step


array([[0.51333195, 0.3334337 , 0.15323426],
       [0.06924401, 0.2065127 , 0.7242432 ],
       [0.3559177 , 0.3266958 , 0.31738657],
       [       nan,        nan,        nan],
       [0.23409691, 0.31738135, 0.44852167],
       [0.4068979 , 0.33663195, 0.2564701 ],
       [0.11671028, 0.31974438, 0.56354535],
       [0.22570753, 0.3182974 , 0.45599505],
       [0.3876859 , 0.34140506, 0.270909  ],
       [0.06655291, 0.22276734, 0.71067977]], dtype=float32)

In [14]:
diff_model_3 = load_model('third_diff_model.h5')

In [15]:
GW1_predictions_3 = np.argmax(diff_model_3.predict(GW1), axis=1)
GW1_predictions_3

1/1 [==============================] - 0s 157ms/step


array([0, 2, 0, 2, 2, 0, 2, 2, 0, 2], dtype=int64)

In [16]:
diff_model_3.predict(GW1)

1/1 [==============================] - 0s 41ms/step


array([[0.4422066 , 0.28969678, 0.26809657],
       [0.12417982, 0.17659023, 0.69922996],
       [0.44354412, 0.2919971 , 0.2644588 ],
       [0.3285526 , 0.31326988, 0.35817745],
       [0.2960585 , 0.28977057, 0.41417083],
       [0.50709975, 0.25808614, 0.23481414],
       [0.12427181, 0.23521571, 0.6405124 ],
       [0.35028026, 0.28113088, 0.36858884],
       [0.46827108, 0.22810422, 0.3036247 ],
       [0.12420639, 0.15168022, 0.72411346]], dtype=float32)