In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW2 = pd.read_csv('GW2.csv')
GW2

Unnamed: 0        HomeTeam          AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  \
0        5712   Nott'm Forest  Sheffield United  NaN   NaN   NaN NaN NaN  NaN   
1        5713          Fulham         Brentford  NaN   NaN   NaN NaN NaN  NaN   
2        5714       Liverpool       Bournemouth  NaN   NaN   NaN NaN NaN  NaN   
3        5715          Wolves          Brighton  NaN   NaN   NaN NaN NaN  NaN   
4        5716       Tottenham        Man United  NaN   NaN   NaN NaN NaN  NaN   
5        5717        Man City         Newcastle  NaN   NaN   NaN NaN NaN  NaN   
6        5718     Aston Villa           Everton  NaN   NaN   NaN NaN NaN  NaN   
7        5719        West Ham           Chelsea  NaN   NaN   NaN NaN NaN  NaN   
8        5720  Crystal Palace           Arsenal  NaN   NaN   NaN NaN NaN  NaN   

   AST  HF  AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  \
0  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.333333   0.266667   
1  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.500000  -0.083333   
2  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  1.833333   1.100000   
3  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.000000  -0.283333   
4  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -1.333333  -1.100000   
5  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.708333   0.750000   
6  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.000000   0.800000   
7  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  1.166667   0.400000   
8  NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -0.166667   0.333333   

   PtsDiff20   GSDiff5  GSDiff10  GSDiff20   GCDiff5  GCDiff10  GCDiff20  \
0   0.100000  1.666667  1.100000  0.681818  1.166667  0.350000  0.081818   
1  -0.322727  1.333333  0.333333 -0.218182  0.833333  0.333333  0.181818   
2   0.818182  1.500000  1.500000  1.136364 -0.666667 -0.200000 -0.409091   
3  -0.409091 -1.333333 -1.366667 -0.909091 -0.666667  0.033333  0.136364   
4  -0.363636  0.041667  0.400000  0.227273  1.083333  1.800000  0.636364   
5   0.745455 -0.958333 -0.216667  0.409091 -0.916667 -0.816667 -0.513636   
6   0.586364 -0.666667  0.200000  0.595455  0.500000 -0.600000 -0.145455   
7   0.436364  0.333333  0.583333  0.581818 -0.666667 -0.050000  0.277273   
8  -0.590909 -0.500000 -0.250000 -1.136364 -0.166667 -0.616667 -0.363636   

     SDiff5   SDiff10   SDiff20   STDiff5  STDiff10  STDiff20    FDiff5  \
0 -1.666667 -0.616667  0.881818  1.166667  1.133333  0.759091  2.000000   
1  1.000000 -0.750000 -0.104545  0.166667 -0.833333 -0.690909  1.500000   
2  8.000000  4.600000  4.500000  2.333333  0.600000  1.545455  5.500000   
3 -6.333333 -7.033333 -7.727273 -3.333333 -3.100000 -3.045455  0.833333   
4 -8.125000 -5.300000 -3.045455 -1.291667 -1.100000 -1.045455  2.541667   
5 -4.000000 -2.200000 -0.790909 -3.291667 -0.483333  0.295455 -2.958333   
6 -2.000000 -2.700000 -0.931818 -1.166667 -1.700000 -0.745455  0.166667   
7 -0.166667 -0.366667 -2.054545 -0.833333 -0.116667 -0.436364 -1.333333   
8  3.000000  0.866667 -3.909091 -0.500000 -0.900000 -1.772727 -2.166667   

    FDiff10   FDiff20    CDiff5   CDiff10   CDiff20    YDiff5   YDiff10  \
0 -0.050000  0.259091 -1.500000 -1.066667 -0.822727 -0.833333 -0.100000   
1  0.500000  0.586364  1.000000  1.166667  0.595455 -0.666667 -0.333333   
2  2.500000  1.909091  2.166667  1.600000  1.409091  1.166667 -0.100000   
3  0.733333  0.954545  1.500000  0.333333 -1.181818 -0.333333  0.500000   
4 -0.300000  1.727273 -0.375000 -1.300000 -1.272727  1.458333  0.200000   
5 -2.750000 -0.695455 -2.000000 -2.933333 -1.445455 -1.875000 -0.616667   
6 -0.700000 -0.354545 -0.166667 -0.500000 -0.136364  1.500000  1.300000   
7 -0.066667 -0.650000  1.500000  0.483333  0.195455 -0.833333 -1.116667   
8 -0.233333  2.272727  0.833333  1.100000 -1.227273 -0.333333 -0.150000   

    YDiff20  RDiff5  RDiff10   RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0  0.277273       0      0.0 -0.050000   0   0            0            0   
1  0.181818       0      0

In [3]:
GW2 = GW2[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW2

PtsDiff5  PtsDiff10  PtsDiff20   GSDiff5  GSDiff10  GSDiff20   GCDiff5  \
0  0.333333   0.266667   0.100000  1.666667  1.100000  0.681818  1.166667   
1  0.500000  -0.083333  -0.322727  1.333333  0.333333 -0.218182  0.833333   
2  1.833333   1.100000   0.818182  1.500000  1.500000  1.136364 -0.666667   
3  0.000000  -0.283333  -0.409091 -1.333333 -1.366667 -0.909091 -0.666667   
4 -1.333333  -1.100000  -0.363636  0.041667  0.400000  0.227273  1.083333   
5  0.708333   0.750000   0.745455 -0.958333 -0.216667  0.409091 -0.916667   
6  0.000000   0.800000   0.586364 -0.666667  0.200000  0.595455  0.500000   
7  1.166667   0.400000   0.436364  0.333333  0.583333  0.581818 -0.666667   
8 -0.166667   0.333333  -0.590909 -0.500000 -0.250000 -1.136364 -0.166667   

   GCDiff10  GCDiff20    SDiff5   SDiff10   SDiff20   STDiff5  STDiff10  \
0  0.350000  0.081818 -1.666667 -0.616667  0.881818  1.166667  1.133333   
1  0.333333  0.181818  1.000000 -0.750000 -0.104545  0.166667 -0.833333   
2 -0.200000 -0.409091  8.000000  4.600000  4.500000  2.333333  0.600000   
3  0.033333  0.136364 -6.333333 -7.033333 -7.727273 -3.333333 -3.100000   
4  1.800000  0.636364 -8.125000 -5.300000 -3.045455 -1.291667 -1.100000   
5 -0.816667 -0.513636 -4.000000 -2.200000 -0.790909 -3.291667 -0.483333   
6 -0.600000 -0.145455 -2.000000 -2.700000 -0.931818 -1.166667 -1.700000   
7 -0.050000  0.277273 -0.166667 -0.366667 -2.054545 -0.833333 -0.116667   
8 -0.616667 -0.363636  3.000000  0.866667 -3.909091 -0.500000 -0.900000   

   STDiff20    FDiff5   FDiff10   FDiff20    CDiff5   CDiff10   CDiff20  \
0  0.759091  2.000000 -0.050000  0.259091 -1.500000 -1.066667 -0.822727   
1 -0.690909  1.500000  0.500000  0.586364  1.000000  1.166667  0.595455   
2  1.545455  5.500000  2.500000  1.909091  2.166667  1.600000  1.409091   
3 -3.045455  0.833333  0.733333  0.954545  1.500000  0.333333 -1.181818   
4 -1.045455  2.541667 -0.300000  1.727273 -0.375000 -1.300000 -1.272727   
5  0.295455 -2.958333 -2.750000 -0.695455 -2.000000 -2.933333 -1.445455   
6 -0.745455  0.166667 -0.700000 -0.354545 -0.166667 -0.500000 -0.136364   
7 -0.436364 -1.333333 -0.066667 -0.650000  1.500000  0.483333  0.195455   
8 -1.772727 -2.166667 -0.233333  2.272727  0.833333  1.100000 -1.227273   

     YDiff5   YDiff10   YDiff20  RDiff5  RDiff10   RDiff20  H1  A1  \
0 -0.833333 -0.100000  0.277273       0      0.0 -0.050000   0   0   
1 -0.666667 -0.333333  0.181818       0      0.0 -0.050000   3   1   
2  1.166667 -0.100000  0.045455       0      0.0  0.000000   1   1   
3 -0.333333  0.500000  0.681818       0      0.0  0.090909   0   3   
4  1.458333  0.200000  0.500000       0      0.0  0.090909   1   3   
5 -1.875000 -0.616667 -0.272727       0      0.0 -0.050000   3   3   
6  1.500000  1.300000  0.054545       0     -0.1 -0.100000   0   0   
7 -0.833333 -1.116667 -0.804545       0      0.0  0.000000   1   1   
8 -0.333333 -0.150000  1.090909       0      0.0  0.045455   3   3   

   HWinStreak3  AWinStreak3  HWinStreak5  AWinStreak5  HLossStreak3  \
0            0            0            0            0             0   
1            0            0            0            0             0   
2            0            0            0            0             0   
3            0            0            0            0             0   
4            0            1            0            1             0   
5            0            0            0            0             0   
6            0            0            0            0             0   
7            0            0            0            0             0   
8            0            0            0            0             0   

   ALossStreak3  HLossStreak3  ALossStreak5   GDDiff5  GDDiff10  GDDiff20  
0             0             0             0  0.500000  0.750000  0.600000  
1             0             0             0  0.500000  0.000000 -0.400000  
2             0             0             0  2.166667  1.700000  1.545455  
3             

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW2_predictions = np.argmax(diff_model.predict(GW2), axis=1)
GW2_predictions

1/1 [==============================] - 0s 409ms/step


array([2, 2, 2, 0, 0, 2, 2, 2, 0], dtype=int64)

In [7]:
diff_model.predict(GW2)

1/1 [==============================] - 0s 25ms/step


array([[2.07790196e-01, 1.72517136e-01, 3.36860836e-01, 3.64832906e-03,
        3.40470369e-03, 3.10293748e-03, 4.22237348e-03, 3.59678874e-03,
        3.76564031e-03, 3.67290946e-03, 3.64880753e-03, 3.11807799e-03,
        3.51048657e-03, 4.01409995e-03, 4.64851735e-03, 4.59388085e-03,
        5.78383543e-03, 3.76970950e-03, 5.05759334e-03, 4.61231126e-03,
        3.49369552e-03, 3.43260495e-03, 3.67874093e-03, 4.22198698e-03,
        3.81295825e-03, 4.54366766e-03, 3.16248275e-03, 3.71757615e-03,
        3.90388048e-03, 3.46702803e-03, 3.77830071e-03, 4.89504822e-03,
        5.70308603e-03, 4.00493247e-03, 4.98676486e-03, 3.21623404e-03,
        4.35995962e-03, 6.40406413e-03, 3.30655021e-03, 2.44049449e-03,
        3.27050337e-03, 4.69991378e-03, 3.82767711e-03, 2.97143287e-03,
        3.38575686e-03, 5.02751861e-03, 3.54908197e-03, 3.81030445e-03,
        4.09370987e-03, 3.67441238e-03, 5.48881153e-03, 2.95229163e-03,
        3.32059502e-03, 5.85546950e-03, 4.56916168e-03, 4.132937

In [8]:
GW2_predictions_2 = np.argmax(diff_model_2.predict(GW2), axis=1)
GW2_predictions_2

1/1 [==============================] - 0s 71ms/step


array([2, 2, 2, 0, 0, 2, 2, 2, 0], dtype=int64)

In [9]:
diff_model_2.predict(GW2)

1/1 [==============================] - 0s 21ms/step


array([[0.28719082, 0.24607213, 0.4667371 ],
       [0.28324834, 0.2927251 , 0.42402646],
       [0.10253242, 0.1879807 , 0.70948684],
       [0.5362567 , 0.2820232 , 0.18172006],
       [0.49888775, 0.22634737, 0.2747649 ],
       [0.25808805, 0.24879429, 0.4931177 ],
       [0.21226464, 0.24041803, 0.54731727],
       [0.2583355 , 0.29810506, 0.4435594 ],
       [0.374064  , 0.31753403, 0.30840197]], dtype=float32)

In [ ]:
GW1_predictions_3 = np.argmax(diff_model_3.predict(GW1), axis=1)
GW1_predictions_3

In [ ]:
diff_model_3.predict(GW1)