In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW3 = pd.read_csv('GW3.csv')
GW3

HomeTeam        AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  \
0           Chelsea           Luton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
1       Bournemouth       Tottenham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
2           Arsenal          Fulham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
3         Brentford  Crystal Palace  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
4           Everton          Wolves  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
5        Man United   Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
6          Brighton        West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
7           Burnley     Aston Villa  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
8  Sheffield United        Man City  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
9         Newcastle       Liverpool  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   

   AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.500000   0.600000   0.772727   
1 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -1.000000  -0.100000  -0.400000   
2 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.166667   0.400000   0.890909   
3 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  1.166667   0.500000   0.468182   
4 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.500000  -0.100000  -0.150000   
5 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.666667   0.500000   0.909091   
6 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN  0.000000   0.500000   0.400000   
7 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -1.666667  -0.600000  -0.716667   
8 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -0.666667  -1.600000  -1.795455   
9 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN -0.166667  -0.666667  -0.350000   

    GSDiff5  GSDiff10  GSDiff20   GCDiff5  GCDiff10  GCDiff20     SDiff5  \
0 -0.166667  0.100000 -0.136364 -2.166667 -2.000000 -2.500000   7.333333   
1 -1.500000 -0.800000 -0.750000 -0.333333 -0.500000 -0.050000  -6.000000   
2  0.000000  0.500000  1.118182 -0.500000  0.000000 -0.031818   3.166667   
3  1.000000  0.400000  0.459091 -0.333333 -0.200000 -0.090909  -1.333333   
4  0.000000  0.300000 -0.050000 -0.666667 -0.200000  0.050000   1.666667   
5  0.166667 -0.400000  0.068182 -0.333333 -0.900000 -0.572727  10.666667   
6  0.500000  0.833333  0.650000  0.000000  0.083333 -0.200000   3.166667   
7 -1.333333 -0.600000 -0.733333  0.333333  0.300000  0.216667  -0.500000   
8 -0.500000 -1.600000 -1.822727  0.333333  0.900000  1.013636  -5.166667   
9 -0.333333  0.250000 -0.250000 -0.500000  0.000000  0.150000  -1.666667   

     SDiff10   SDiff20   STDiff5  STDiff10  STDiff20    FDiff5   FDiff10  \
0   4.100000  4.681818  1.833333      1.50  1.227273 -4.166667 -3.200000   
1  -3.400000 -2.800000 -2.833333     -1.70 -1.050000 -0.833333 -0.200000   
2   4.600000  4.404545  1.166667      2.10  1.595455  0.000000 -0.400000   
3  -2.400000 -0.481818  1.166667      1.00  1.181818 -0.666667 -1.400000   
4   2.300000  1.950000  1.166667      1.90  1.100000 -2.166667 -2.000000   
5  10.000000  8.240909  3.333333      3.20  2.818182 -0.833333 -0.300000   
6   5.083333  7.350000  1.500000      1.75  3.100000  4.166667  5.250000   
7   0.200000 -1.175000 -1.500000      0.00 -0.833333 -1.166667 -0.100000   
8  -6.000000 -6.963636 -1.500000     -3.70 -3.577273  0.833333  2.500000   
9  -0.333333 -0.150000  0.166667      1.25  0.150000 -1.833333 -1.583333   

    FDiff20    CDiff5   CDiff10   CDiff20    YDiff5   YDiff10   YDiff20  \
0 -1.954545 -0.500000 -2.300000 -1.409091 -0.500000  0.000000  0.136364   
1 -1.600000 -1.666667 -1.000000 -0.800000  0.166667 -0.100000 -0.100000   
2 -1.977273  1.000000  1.100000  1.900000 -0.666667 -0.200000 -0.750000   
3 -1.113636 -1.333333 -1.800000 -0.950000  1.333333  0.400000 -0.409091   
4 -1.450000  3.666667  0.600000  0.050000 -1.666667 -0.700000 -0.350000   
5 -0.940909  1.666667  2.800000  2.404545 -1.000000  0.200000 -0.518182   
6  2.300000 -1.833333 -0.250000  0.450000  1.833333  1.750000  0.650000   
7 -0.033333 -0.666667 -0.10000

In [3]:
GW3 = GW3[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW3

PtsDiff5  PtsDiff10  PtsDiff20   GSDiff5  GSDiff10  GSDiff20   GCDiff5  \
0  0.500000   0.600000   0.772727 -0.166667  0.100000 -0.136364 -2.166667   
1 -1.000000  -0.100000  -0.400000 -1.500000 -0.800000 -0.750000 -0.333333   
2  0.166667   0.400000   0.890909  0.000000  0.500000  1.118182 -0.500000   
3  1.166667   0.500000   0.468182  1.000000  0.400000  0.459091 -0.333333   
4  0.500000  -0.100000  -0.150000  0.000000  0.300000 -0.050000 -0.666667   
5  0.666667   0.500000   0.909091  0.166667 -0.400000  0.068182 -0.333333   
6  0.000000   0.500000   0.400000  0.500000  0.833333  0.650000  0.000000   
7 -1.666667  -0.600000  -0.716667 -1.333333 -0.600000 -0.733333  0.333333   
8 -0.666667  -1.600000  -1.795455 -0.500000 -1.600000 -1.822727  0.333333   
9 -0.166667  -0.666667  -0.350000 -0.333333  0.250000 -0.250000 -0.500000   

   GCDiff10  GCDiff20     SDiff5    SDiff10   SDiff20   STDiff5  STDiff10  \
0 -2.000000 -2.500000   7.333333   4.100000  4.681818  1.833333      1.50   
1 -0.500000 -0.050000  -6.000000  -3.400000 -2.800000 -2.833333     -1.70   
2  0.000000 -0.031818   3.166667   4.600000  4.404545  1.166667      2.10   
3 -0.200000 -0.090909  -1.333333  -2.400000 -0.481818  1.166667      1.00   
4 -0.200000  0.050000   1.666667   2.300000  1.950000  1.166667      1.90   
5 -0.900000 -0.572727  10.666667  10.000000  8.240909  3.333333      3.20   
6  0.083333 -0.200000   3.166667   5.083333  7.350000  1.500000      1.75   
7  0.300000  0.216667  -0.500000   0.200000 -1.175000 -1.500000      0.00   
8  0.900000  1.013636  -5.166667  -6.000000 -6.963636 -1.500000     -3.70   
9  0.000000  0.150000  -1.666667  -0.333333 -0.150000  0.166667      1.25   

   STDiff20    FDiff5   FDiff10   FDiff20    CDiff5   CDiff10   CDiff20  \
0  1.227273 -4.166667 -3.200000 -1.954545 -0.500000 -2.300000 -1.409091   
1 -1.050000 -0.833333 -0.200000 -1.600000 -1.666667 -1.000000 -0.800000   
2  1.595455  0.000000 -0.400000 -1.977273  1.000000  1.100000  1.900000   
3  1.181818 -0.666667 -1.400000 -1.113636 -1.333333 -1.800000 -0.950000   
4  1.100000 -2.166667 -2.000000 -1.450000  3.666667  0.600000  0.050000   
5  2.818182 -0.833333 -0.300000 -0.940909  1.666667  2.800000  2.404545   
6  3.100000  4.166667  5.250000  2.300000 -1.833333 -0.250000  0.450000   
7 -0.833333 -1.166667 -0.100000 -0.033333 -0.666667 -0.100000  0.383333   
8 -3.577273  0.833333  2.500000  1.545455  1.833333 -0.200000 -1.700000   
9  0.150000 -1.833333 -1.583333 -1.200000 -2.500000  1.333333  1.000000   

     YDiff5   YDiff10   YDiff20    RDiff5   RDiff10   RDiff20  H1  A1  \
0 -0.500000  0.000000  0.136364  0.000000  0.000000  0.000000   0   0   
1  0.166667 -0.100000 -0.100000  0.000000  0.000000 -0.100000   0   3   
2 -0.666667 -0.200000 -0.750000  0.000000  0.000000 -0.004545   3   0   
3  1.333333  0.400000 -0.409091  0.000000  0.000000  0.004545   3   0   
4 -1.666667 -0.700000 -0.350000 -0.166667  0.000000 -0.050000   0   0   
5 -1.000000  0.200000 -0.518182  0.000000  0.000000  0.045455   0   3   
6  1.833333  1.750000  0.650000 -0.166667 -0.083333 -0.050000   3   3   
7 -2.833333 -1.300000 -0.516667  0.333333  0.200000  0.166667   0   3   
8  2.500000  1.400000  0.777273  0.000000  0.000000  0.050000   0   3   
9  0.000000  0.333333 -0.300000 -0.166667 -0.083333  0.000000   0   3   

   HWinStreak3  AWinStreak3  HWinStreak5  AWinStreak5  HLossStreak3  \
0            0            0            0            0             0   
1            0            0            0            0             0   
2            1            0            0            0             0   
3            0            0            0            0             0   
4            0            0            0            0             0   
5            0            0            0            0             0   
6            0            0            0            0             0   
7            0            0            0            0             0   
8            0            0           

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW3_predictions = np.argmax(diff_model.predict(GW3), axis=1)
GW3_predictions

1/1 [==============================] - 0s 216ms/step


array([2, 0, 2, 2, 2, 2, 2, 0, 0, 2], dtype=int64)

In [7]:
diff_model.predict(GW3)

1/1 [==============================] - 0s 42ms/step


array([[8.15818906e-02, 1.75143436e-01, 6.23996437e-01, 1.88670284e-03,
        1.61144265e-03, 1.35479239e-03, 2.26518046e-03, 1.99108268e-03,
        2.64697662e-03, 1.22899597e-03, 1.84787251e-03, 1.56851800e-03,
        2.48797308e-03, 1.57808617e-03, 1.45391352e-03, 1.63408881e-03,
        1.59643008e-03, 1.65118591e-03, 1.86694902e-03, 1.74057134e-03,
        1.76178582e-03, 2.34433985e-03, 1.13352982e-03, 1.07901613e-03,
        1.35738624e-03, 2.03237496e-03, 1.76787586e-03, 9.72712005e-04,
        2.38137483e-03, 1.92488369e-03, 1.45815976e-03, 1.84727961e-03,
        1.79897260e-03, 1.32117991e-03, 2.85228202e-03, 2.30878592e-03,
        1.54072302e-03, 1.60248950e-03, 9.77612566e-04, 1.31160370e-03,
        1.34082139e-03, 2.25001248e-03, 2.22310470e-03, 1.34945987e-03,
        1.23742025e-03, 1.36716757e-03, 1.25828001e-03, 1.27647864e-03,
        1.24252157e-03, 1.17098400e-03, 1.58837298e-03, 1.31184258e-03,
        2.40947912e-03, 1.41549692e-03, 1.11593213e-03, 1.784281

In [8]:
GW3_predictions_2 = np.argmax(diff_model_2.predict(GW3), axis=1)
GW3_predictions_2

1/1 [==============================] - 0s 155ms/step


array([2, 0, 2, 2, 2, 2, 2, 0, 0, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW3)

1/1 [==============================] - 0s 48ms/step


array([[0.12082826, 0.16354693, 0.71562487],
       [0.38841984, 0.2803955 , 0.33118466],
       [0.11610893, 0.19140786, 0.69248325],
       [0.25646573, 0.22082761, 0.5227066 ],
       [0.23513532, 0.2845046 , 0.48036006],
       [0.08559805, 0.2080299 , 0.7063719 ],
       [0.12851818, 0.16316879, 0.7083131 ],
       [0.36855188, 0.3103506 , 0.32109752],
       [0.6529621 , 0.23356119, 0.11347667],
       [0.26421195, 0.25783014, 0.47795787]], dtype=float32)

In [10]:
GW3_predictions_3 = np.argmax(diff_model_3.predict(GW3), axis=1)
GW3_predictions_3

1/1 [==============================] - 0s 199ms/step


array([2, 0, 2, 2, 2, 2, 2, 0, 0, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW3)

1/1 [==============================] - 0s 53ms/step


array([[0.15476942, 0.189194  , 0.6560365 ],
       [0.35873842, 0.2989085 , 0.34235305],
       [0.18042506, 0.24249709, 0.57707787],
       [0.28209582, 0.25993195, 0.4579722 ],
       [0.25715095, 0.25980628, 0.48304278],
       [0.07735298, 0.16889386, 0.7537532 ],
       [0.1260737 , 0.2501223 , 0.623804  ],
       [0.38098094, 0.29431686, 0.32470223],
       [0.5873957 , 0.22976595, 0.1828383 ],
       [0.34013596, 0.24839252, 0.4114715 ]], dtype=float32)