In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW4 = pd.read_csv('GW4.csv')
GW4

HomeTeam       AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  AF  \
0             Luton       West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
1  Sheffield United        Everton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
2         Brentford    Bournemouth  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
3           Burnley      Tottenham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
4           Chelsea  Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
5          Man City         Fulham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
6          Brighton      Newcastle  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
7    Crystal Palace         Wolves  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
8         Liverpool    Aston Villa  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
9           Arsenal     Man United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   

   HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN   NaN   NaN -2.166667  -1.333333  -1.400000   
1 NaN NaN NaN NaN NaN NaN   NaN   NaN -0.333333   0.000000  -0.218182   
2 NaN NaN NaN NaN NaN NaN   NaN   NaN  2.166667   1.166667   0.368182   
3 NaN NaN NaN NaN NaN NaN   NaN   NaN -1.500000  -0.250000  -0.508333   
4 NaN NaN NaN NaN NaN NaN   NaN   NaN -0.833333  -0.766667   0.000000   
5 NaN NaN NaN NaN NaN NaN   NaN   NaN  1.375000   1.416667   1.363636   
6 NaN NaN NaN NaN NaN NaN   NaN   NaN  0.166667   0.000000  -0.018182   
7 NaN NaN NaN NaN NaN NaN   NaN   NaN  0.333333  -0.033333   0.000000   
8 NaN NaN NaN NaN NaN NaN   NaN   NaN -0.500000   0.483333   0.272727   
9 NaN NaN NaN NaN NaN NaN   NaN   NaN  0.166667  -0.083333   0.181818   

    GSDiff5  GSDiff10  GSDiff20   GCDiff5  GCDiff10  GCDiff20    SDiff5  \
0 -1.833333 -1.000000 -1.050000  2.333333  1.916667  1.900000 -5.666667   
1  0.000000 -0.500000 -0.445455 -0.166667 -0.400000 -0.022727 -6.500000   
2  1.833333  0.833333  0.404545 -0.666667 -1.000000 -0.631818  1.833333   
3 -1.500000 -0.750000 -0.883333  0.333333 -0.416667 -0.200000 -9.000000   
4  0.000000 -0.866667 -0.318182  1.000000 -0.033333 -0.409091  7.666667   
5 -0.083333  0.250000  1.045455 -1.458333 -1.250000 -0.681818  6.791667   
6  0.666667 -0.166667  0.090909  0.666667  0.583333  0.204545  1.333333   
7  0.333333  0.266667  0.227273 -1.000000 -0.650000 -0.500000  2.333333   
8 -0.166667  0.700000  0.772727  0.000000  0.116667 -0.136364  3.833333   
9  0.416667  0.666667  1.000000 -0.666667  0.750000  0.090909 -6.000000   

    SDiff10   SDiff20   STDiff5  STDiff10  STDiff20    FDiff5   FDiff10  \
0 -1.416667 -1.550000 -3.500000 -1.833333 -1.900000  2.500000  3.583333   
1 -5.400000 -5.281818 -3.500000 -3.500000 -2.531818 -0.333333  0.200000   
2 -0.500000  0.963636  1.000000  0.916667  0.622727 -1.166667 -0.750000   
3 -1.833333 -3.525000 -4.333333 -1.666667 -1.875000  1.166667 -0.250000   
4  4.783333  5.181818  2.166667  1.433333  1.409091 -2.166667 -2.300000   
5  7.166667  4.863636  2.000000  2.666667  2.500000 -0.375000 -3.333333   
6  0.166667  2.818182  1.833333  0.083333  1.022727  1.666667  1.666667   
7  3.766667  0.909091  0.833333  1.550000 -0.090909 -2.500000 -2.583333   
8  4.600000  4.181818  0.166667  0.983333  1.363636 -0.666667  2.666667   
9 -5.083333 -2.500000 -0.791667 -0.583333 -0.772727 -0.625000 -0.666667   

    FDiff20    CDiff5   CDiff10   CDiff20    YDiff5   YDiff10   YDiff20  \
0  2.700000 -0.166667  1.000000 -0.200000  0.500000  1.333333  1.200000   
1  0.131818 -3.500000 -1.800000 -0.395455  1.000000  0.500000  0.045455   
2 -0.300000 -0.666667 -0.083333  0.340909 -0.500000 -0.083333 -0.550000   
3 -0.791667 -0.666667  0.250000  0.916667 -0.333333 -0.416667 -0.466667   
4 -1.454545  2.500000  2.183333  2.090909 -1.000000  0.083333  0.000000   
5 -1.545455 -0.750000  2.250000  1.681818 -1.875000 -0.916667 -0.636364   
6  0.218182  1.333333 -2.083333 -0.154545  1.166667  0.916667  0.172727   
7 -1.590909  1.333333  1.466667  0.045455 -3.000000 -1.783333 -

In [3]:
GW4 = GW4[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW4

PtsDiff5  PtsDiff10  PtsDiff20   GSDiff5  GSDiff10  GSDiff20   GCDiff5  \
0 -2.166667  -1.333333  -1.400000 -1.833333 -1.000000 -1.050000  2.333333   
1 -0.333333   0.000000  -0.218182  0.000000 -0.500000 -0.445455 -0.166667   
2  2.166667   1.166667   0.368182  1.833333  0.833333  0.404545 -0.666667   
3 -1.500000  -0.250000  -0.508333 -1.500000 -0.750000 -0.883333  0.333333   
4 -0.833333  -0.766667   0.000000  0.000000 -0.866667 -0.318182  1.000000   
5  1.375000   1.416667   1.363636 -0.083333  0.250000  1.045455 -1.458333   
6  0.166667   0.000000  -0.018182  0.666667 -0.166667  0.090909  0.666667   
7  0.333333  -0.033333   0.000000  0.333333  0.266667  0.227273 -1.000000   
8 -0.500000   0.483333   0.272727 -0.166667  0.700000  0.772727  0.000000   
9  0.166667  -0.083333   0.181818  0.416667  0.666667  1.000000 -0.666667   

   GCDiff10  GCDiff20    SDiff5   SDiff10   SDiff20   STDiff5  STDiff10  \
0  1.916667  1.900000 -5.666667 -1.416667 -1.550000 -3.500000 -1.833333   
1 -0.400000 -0.022727 -6.500000 -5.400000 -5.281818 -3.500000 -3.500000   
2 -1.000000 -0.631818  1.833333 -0.500000  0.963636  1.000000  0.916667   
3 -0.416667 -0.200000 -9.000000 -1.833333 -3.525000 -4.333333 -1.666667   
4 -0.033333 -0.409091  7.666667  4.783333  5.181818  2.166667  1.433333   
5 -1.250000 -0.681818  6.791667  7.166667  4.863636  2.000000  2.666667   
6  0.583333  0.204545  1.333333  0.166667  2.818182  1.833333  0.083333   
7 -0.650000 -0.500000  2.333333  3.766667  0.909091  0.833333  1.550000   
8  0.116667 -0.136364  3.833333  4.600000  4.181818  0.166667  0.983333   
9  0.750000  0.090909 -6.000000 -5.083333 -2.500000 -0.791667 -0.583333   

   STDiff20    FDiff5   FDiff10   FDiff20    CDiff5   CDiff10   CDiff20  \
0 -1.900000  2.500000  3.583333  2.700000 -0.166667  1.000000 -0.200000   
1 -2.531818 -0.333333  0.200000  0.131818 -3.500000 -1.800000 -0.395455   
2  0.622727 -1.166667 -0.750000 -0.300000 -0.666667 -0.083333  0.340909   
3 -1.875000  1.166667 -0.250000 -0.791667 -0.666667  0.250000  0.916667   
4  1.409091 -2.166667 -2.300000 -1.454545  2.500000  2.183333  2.090909   
5  2.500000 -0.375000 -3.333333 -1.545455 -0.750000  2.250000  1.681818   
6  1.022727  1.666667  1.666667  0.218182  1.333333 -2.083333 -0.154545   
7 -0.090909 -2.500000 -2.583333 -1.590909  1.333333  1.466667  0.045455   
8  1.363636 -0.666667  2.666667  1.000000  3.333333  1.000000  1.363636   
9 -0.772727 -0.625000 -0.666667 -1.954545  0.958333 -0.333333  0.318182   

     YDiff5   YDiff10   YDiff20    RDiff5   RDiff10   RDiff20  H1  A1  \
0  0.500000  1.333333  1.200000 -0.166667 -0.083333 -0.050000   0   3   
1  1.000000  0.500000  0.045455  0.000000 -0.100000 -0.054545   0   0   
2 -0.500000 -0.083333 -0.550000  0.000000  0.000000  0.050000   1   0   
3 -0.333333 -0.416667 -0.466667  0.333333  0.166667  0.066667   0   3   
4 -1.000000  0.083333  0.000000 -0.166667 -0.083333 -0.045455   3   0   
5 -1.875000 -0.916667 -0.636364 -0.333333 -0.166667 -0.090909   3   1   
6  1.166667  0.916667  0.172727  0.000000  0.000000 -0.050000   0   0   
7 -3.000000 -1.783333 -0.681818 -0.166667 -0.083333 -0.090909   1   3   
8 -1.000000 -0.850000 -0.090909  0.333333  0.200000  0.090909   3   3   
9 -1.333333 -1.416667 -0.818182  0.166667  0.083333  0.045455   1   3   

   HWinStreak3  AWinStreak3  HWinStreak5  AWinStreak5  HLossStreak3  \
0            0            0            0            0             0   
1            0            0            0            0             1   
2            0            0            0            0             0   
3            0            0            0            0             1   
4            0            0            0            0             0   
5            1            0            0            0             0   
6            0            0            0            0             0   
7            0            0            0            0             0   
8            0            0            0            0       

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW4_predictions = np.argmax(diff_model.predict(GW4), axis=1)
GW4_predictions

1/1 [==============================] - 0s 210ms/step


array([0, 0, 2, 0, 2, 2, 2, 2, 2, 2], dtype=int64)

In [7]:
diff_model.predict(GW4)

1/1 [==============================] - 0s 39ms/step


array([[5.57062626e-01, 2.53232747e-01, 1.82325169e-01, 1.47947445e-04,
        7.16076320e-05, 6.96165516e-05, 7.06457140e-05, 1.03382517e-04,
        1.57455448e-04, 4.74198860e-05, 7.24980928e-05, 1.19140619e-04,
        1.14338451e-04, 6.72711321e-05, 9.52204573e-05, 8.47027768e-05,
        3.00477463e-04, 1.16919153e-04, 9.98914911e-05, 2.07186444e-04,
        1.04642262e-04, 8.78104111e-05, 1.02565849e-04, 1.21457320e-04,
        1.84025266e-04, 8.83796965e-05, 7.97442553e-05, 6.20075298e-05,
        1.00258927e-04, 6.21000290e-05, 7.89961123e-05, 1.36778661e-04,
        1.29521664e-04, 6.40921935e-05, 1.90051098e-04, 1.05203610e-04,
        1.13662762e-04, 1.52404376e-04, 7.60756666e-05, 9.33514748e-05,
        8.04351803e-05, 6.64576000e-05, 7.89967089e-05, 9.71598274e-05,
        8.21956128e-05, 7.50320542e-05, 9.33942210e-05, 1.12619804e-04,
        1.75298628e-04, 1.48579769e-04, 1.21495083e-04, 4.10003122e-05,
        4.90825514e-05, 1.35182563e-04, 8.93125616e-05, 1.027971

In [8]:
GW4_predictions_2 = np.argmax(diff_model_2.predict(GW4), axis=1)
GW4_predictions_2

1/1 [==============================] - 0s 132ms/step


array([0, 0, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW4)

1/1 [==============================] - 0s 45ms/step


array([[0.520986  , 0.306622  , 0.17239182],
       [0.44547835, 0.26806208, 0.28645954],
       [0.17867221, 0.22782265, 0.59350514],
       [0.3465739 , 0.3023902 , 0.35103595],
       [0.15284258, 0.24860658, 0.59855086],
       [0.08326373, 0.16879979, 0.7479364 ],
       [0.27895194, 0.23464328, 0.48640478],
       [0.2187913 , 0.27050337, 0.51070535],
       [0.1313058 , 0.22352335, 0.6451708 ],
       [0.29014   , 0.2408604 , 0.46899962]], dtype=float32)

In [10]:
GW4_predictions_3 = np.argmax(diff_model_3.predict(GW4), axis=1)
GW4_predictions_3

1/1 [==============================] - 0s 125ms/step


array([0, 0, 2, 0, 2, 2, 2, 2, 2, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW4)

1/1 [==============================] - 0s 42ms/step


array([[0.56085587, 0.22159846, 0.21754561],
       [0.4048289 , 0.28125647, 0.3139146 ],
       [0.24590898, 0.2085518 , 0.54553926],
       [0.39726207, 0.32367668, 0.2790613 ],
       [0.17405005, 0.18089396, 0.645056  ],
       [0.10885333, 0.23786731, 0.65327936],
       [0.27131194, 0.25446418, 0.47422385],
       [0.21187146, 0.27328372, 0.51484483],
       [0.19800882, 0.26766142, 0.5343298 ],
       [0.31175172, 0.23638527, 0.451863  ]], dtype=float32)