In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW5 = pd.read_csv('GW5.csv')
GW5

HomeTeam          AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  AF  \
0         Wolves         Liverpool  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
1    Aston Villa    Crystal Palace  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
2         Fulham             Luton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
3     Man United          Brighton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
4      Tottenham  Sheffield United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
5       West Ham          Man City  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
6        Everton           Arsenal  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
7    Bournemouth           Chelsea  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
8      Newcastle         Brentford  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
9  Nott'm Forest           Burnley  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   

   HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN   NaN   NaN -1.958333  -1.000000  -1.009091   
1 NaN NaN NaN NaN NaN NaN   NaN   NaN  0.166667   0.333333   0.636364   
2 NaN NaN NaN NaN NaN NaN   NaN   NaN  0.500000   1.166667   1.272727   
3 NaN NaN NaN NaN NaN NaN   NaN   NaN  0.000000   0.216667   0.081818   
4 NaN NaN NaN NaN NaN NaN   NaN   NaN  2.250000   0.666667   1.090909   
5 NaN NaN NaN NaN NaN NaN   NaN   NaN -0.125000  -0.500000  -1.136364   
6 NaN NaN NaN NaN NaN NaN   NaN   NaN -2.083333  -0.933333  -1.277273   
7 NaN NaN NaN NaN NaN NaN   NaN   NaN -0.125000  -0.100000   0.316667   
8 NaN NaN NaN NaN NaN NaN   NaN   NaN -1.083333  -0.833333   0.104545   
9 NaN NaN NaN NaN NaN NaN   NaN   NaN  1.500000   0.702381  -0.041667   

    GSDiff5  GSDiff10  GSDiff20   GCDiff5  GCDiff10  GCDiff20    SDiff5  \
0 -1.791667 -1.583333 -1.436364  1.791667  0.583333  0.536364 -5.666667   
1  0.833333  0.016667  0.500000  1.000000 -0.050000  0.045455 -5.166667   
2 -0.125000  1.000000  0.613636 -0.125000 -0.666667 -1.204545 -3.875000   
3 -1.166667 -0.766667 -0.877273  0.000000 -0.816667 -0.354545  1.500000   
4  1.625000  1.500000  1.545455 -1.000000  0.000000 -0.136364  8.375000   
5  0.375000 -0.314286 -0.818182  0.625000  0.785714  0.863636 -3.875000   
6 -1.500000 -0.633333 -1.454545  1.500000  0.483333  0.477273 -1.625000   
7 -0.291667 -0.300000  0.050000 -0.208333 -0.100000  0.208333 -5.666667   
8 -0.083333  0.000000  0.545455  0.875000  0.666667  0.304545 -1.041667   
9  0.625000  0.940476  0.363636 -0.875000 -0.059524  0.151515  1.250000   

    SDiff10   SDiff20   STDiff5  STDiff10  STDiff20    FDiff5   FDiff10  \
0 -6.916667 -4.254545 -2.166667 -2.333333 -1.459091  1.875000  0.750000   
1 -3.416667 -1.090909 -1.000000 -1.200000  0.227273  0.166667 -1.750000   
2 -3.500000 -2.500000  1.000000  1.916667  1.909091  0.625000  0.250000   
3  1.933333 -1.195455 -1.666667 -0.333333 -0.827273 -2.333333 -2.883333   
4  5.416667  6.318182  3.375000  3.583333  2.863636 -1.625000 -0.750000   
5 -2.885714 -3.045455 -1.000000 -0.628571 -1.590909  2.750000  0.857143   
6  1.400000 -1.490909 -0.041667  0.083333 -0.309091  2.416667  0.550000   
7 -3.800000 -3.291667 -0.208333 -1.200000 -0.441667  2.958333  1.800000   
8  4.333333  4.018182  0.583333  1.083333  0.909091  2.291667  3.166667   
9 -3.345238 -2.026515 -0.375000 -0.714286  0.053030 -7.625000  0.035714   

    FDiff20    CDiff5   CDiff10   CDiff20    YDiff5   YDiff10   YDiff20  \
0  0.786364 -4.041667 -2.583333 -0.950000  1.250000  1.250000  0.595455   
1 -0.863636  0.500000  0.016667 -0.818182  2.166667  1.366667  0.454545   
2  0.954545 -2.750000 -3.166667 -2.522727  0.625000 -0.250000  0.022727   
3 -0.559091  0.333333  1.166667  0.081818 -0.833333 -0.533333 -0.054545   
4 -0.272727 -1.375000  0.583333  0.227273 -1.000000 -0.166667  0.090909   
5  0.181818 -1.291667 -0.528571  0.318182  1.458333  0.885714  0.045455   
6  2.400000 -1.166667  0.266667 -2.045455  1.333333  1.000000  0.950000   
7  0.941667 -2.500000 -1.300000 -1.533333 -0.666667 -0.40000

In [3]:
GW5 = GW5[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW5

PtsDiff5  PtsDiff10  PtsDiff20   GSDiff5  GSDiff10  GSDiff20   GCDiff5  \
0 -1.958333  -1.000000  -1.009091 -1.791667 -1.583333 -1.436364  1.791667   
1  0.166667   0.333333   0.636364  0.833333  0.016667  0.500000  1.000000   
2  0.500000   1.166667   1.272727 -0.125000  1.000000  0.613636 -0.125000   
3  0.000000   0.216667   0.081818 -1.166667 -0.766667 -0.877273  0.000000   
4  2.250000   0.666667   1.090909  1.625000  1.500000  1.545455 -1.000000   
5 -0.125000  -0.500000  -1.136364  0.375000 -0.314286 -0.818182  0.625000   
6 -2.083333  -0.933333  -1.277273 -1.500000 -0.633333 -1.454545  1.500000   
7 -0.125000  -0.100000   0.316667 -0.291667 -0.300000  0.050000 -0.208333   
8 -1.083333  -0.833333   0.104545 -0.083333  0.000000  0.545455  0.875000   
9  1.500000   0.702381  -0.041667  0.625000  0.940476  0.363636 -0.875000   

   GCDiff10  GCDiff20    SDiff5   SDiff10   SDiff20   STDiff5  STDiff10  \
0  0.583333  0.536364 -5.666667 -6.916667 -4.254545 -2.166667 -2.333333   
1 -0.050000  0.045455 -5.166667 -3.416667 -1.090909 -1.000000 -1.200000   
2 -0.666667 -1.204545 -3.875000 -3.500000 -2.500000  1.000000  1.916667   
3 -0.816667 -0.354545  1.500000  1.933333 -1.195455 -1.666667 -0.333333   
4  0.000000 -0.136364  8.375000  5.416667  6.318182  3.375000  3.583333   
5  0.785714  0.863636 -3.875000 -2.885714 -3.045455 -1.000000 -0.628571   
6  0.483333  0.477273 -1.625000  1.400000 -1.490909 -0.041667  0.083333   
7 -0.100000  0.208333 -5.666667 -3.800000 -3.291667 -0.208333 -1.200000   
8  0.666667  0.304545 -1.041667  4.333333  4.018182  0.583333  1.083333   
9 -0.059524  0.151515  1.250000 -3.345238 -2.026515 -0.375000 -0.714286   

   STDiff20    FDiff5   FDiff10   FDiff20    CDiff5   CDiff10   CDiff20  \
0 -1.459091  1.875000  0.750000  0.786364 -4.041667 -2.583333 -0.950000   
1  0.227273  0.166667 -1.750000 -0.863636  0.500000  0.016667 -0.818182   
2  1.909091  0.625000  0.250000  0.954545 -2.750000 -3.166667 -2.522727   
3 -0.827273 -2.333333 -2.883333 -0.559091  0.333333  1.166667  0.081818   
4  2.863636 -1.625000 -0.750000 -0.272727 -1.375000  0.583333  0.227273   
5 -1.590909  2.750000  0.857143  0.181818 -1.291667 -0.528571  0.318182   
6 -0.309091  2.416667  0.550000  2.400000 -1.166667  0.266667 -2.045455   
7 -0.441667  2.958333  1.800000  0.941667 -2.500000 -1.300000 -1.533333   
8  0.909091  2.291667  3.166667  1.313636 -1.041667  1.750000  2.140909   
9  0.053030 -7.625000  0.035714  0.071970 -1.875000 -2.761905 -2.181818   

     YDiff5   YDiff10   YDiff20  RDiff5   RDiff10   RDiff20  H1  A1  \
0  1.250000  1.250000  0.595455   0.000 -0.083333 -0.009091   0   3   
1  2.166667  1.366667  0.454545   0.000  0.000000 -0.045455   0   3   
2  0.625000 -0.250000  0.022727   0.625  0.166667  0.090909   0   0   
3 -0.833333 -0.533333 -0.054545   0.000  0.000000  0.000000   0   3   
4 -1.000000 -0.166667  0.090909   0.000  0.000000  0.000000   3   1   
5  1.458333  0.885714  0.045455   0.500  0.142857  0.045455   3   3   
6  1.333333  1.000000  0.950000  -0.500 -0.083333  0.054545   1   3   
7 -0.666667 -0.400000 -0.466667   0.000  0.000000  0.000000   1   0   
8  1.250000  0.500000  0.240909   0.000  0.000000  0.004545   0   1   
9  1.125000  0.380952  0.568182  -0.500 -0.130952 -0.121212   3   0   

   HWinStreak3  AWinStreak3  HWinStreak5  AWinStreak5  HLossStreak3  \
0            0            1            0            0             0   
1            0            0            0            0             0   
2            0            0            0            0             0   
3            0            0            0            0             0   
4            1            0            0            0             0   
5            1            1            0            0             0   
6            0            0            0            0             0   
7            0            0            0            0             0   
8            0            0            0            0             1   
9          

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW5_predictions = np.argmax(diff_model.predict(GW5), axis=1)
GW5_predictions

1/1 [==============================] - 0s 178ms/step


array([0, 2, 2, 1, 2, 0, 0, 0, 2, 2], dtype=int64)

In [7]:
diff_model.predict(GW5)

1/1 [==============================] - 0s 34ms/step


array([[5.61473906e-01, 2.52250522e-01, 1.78382128e-01, 1.69791369e-04,
        8.69325813e-05, 9.07061185e-05, 6.54000614e-05, 1.44701015e-04,
        3.09088471e-04, 4.26291372e-05, 1.12196234e-04, 1.68933708e-04,
        1.44408492e-04, 1.35260052e-04, 9.83873542e-05, 6.93527327e-05,
        1.47121944e-04, 8.60048895e-05, 9.80523910e-05, 9.41026519e-05,
        9.17953803e-05, 1.05407154e-04, 1.34915550e-04, 8.58455824e-05,
        1.60483032e-04, 1.57507980e-04, 9.57141674e-05, 8.01002607e-05,
        1.03933518e-04, 6.33850723e-05, 1.15946656e-04, 1.17614181e-04,
        2.41497255e-04, 6.55831245e-05, 1.84061908e-04, 1.27777748e-04,
        1.02780177e-04, 1.11764683e-04, 5.42924936e-05, 9.90665721e-05,
        9.51889306e-05, 9.11189927e-05, 1.05192856e-04, 8.19170818e-05,
        1.26203493e-04, 8.61684239e-05, 6.47996494e-05, 9.25435816e-05,
        1.18740747e-04, 1.42727164e-04, 1.73241104e-04, 9.30215756e-05,
        9.68569148e-05, 1.72055792e-04, 5.79320731e-05, 1.132332

In [8]:
GW5_predictions_2 = np.argmax(diff_model_2.predict(GW5), axis=1)
GW5_predictions_2

1/1 [==============================] - 0s 133ms/step


array([0, 2, 2, 2, 2, 0, 0, 0, 2, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW5)

1/1 [==============================] - 0s 39ms/step


array([[0.5733649 , 0.24208522, 0.18454975],
       [0.28706762, 0.25437328, 0.45855913],
       [0.251382  , 0.20707227, 0.54154575],
       [0.2716401 , 0.33598614, 0.39237374],
       [0.10384145, 0.16598502, 0.7301736 ],
       [0.47383305, 0.26948348, 0.2566834 ],
       [0.4798148 , 0.26646924, 0.25371596],
       [0.4008431 , 0.23624916, 0.3629077 ],
       [0.17606737, 0.21398528, 0.6099473 ],
       [0.3351352 , 0.256958  , 0.40790683]], dtype=float32)

In [10]:
GW5_predictions_3 = np.argmax(diff_model_3.predict(GW5), axis=1)
GW5_predictions_3

1/1 [==============================] - 0s 124ms/step


array([0, 2, 2, 2, 2, 0, 0, 0, 2, 0], dtype=int64)

In [11]:
diff_model_3.predict(GW5)

1/1 [==============================] - 0s 53ms/step


array([[0.5523791 , 0.22017285, 0.22744812],
       [0.25315177, 0.23817979, 0.5086684 ],
       [0.26580596, 0.1925596 , 0.5416345 ],
       [0.3380936 , 0.28506166, 0.37684476],
       [0.09111468, 0.15949167, 0.7493936 ],
       [0.40522102, 0.29175016, 0.30302873],
       [0.42274067, 0.29193223, 0.285327  ],
       [0.4302889 , 0.281889  , 0.28782216],
       [0.23041579, 0.28306356, 0.48652074],
       [0.37980032, 0.27475625, 0.34544337]], dtype=float32)