In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW6 = pd.read_csv('GW6.csv')
GW6

HomeTeam       AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  AF  \
0    Crystal Palace         Fulham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
1             Luton         Wolves  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
2          Man City  Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
3         Brentford        Everton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
4           Burnley     Man United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
5           Arsenal      Tottenham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
6          Brighton    Bournemouth  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
7           Chelsea    Aston Villa  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
8         Liverpool       West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   
9  Sheffield United      Newcastle  NaN   NaN   NaN NaN NaN  NaN  NaN NaN NaN   

   HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0        0.1       0.10   
1 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.6       -0.7      -1.05   
2 NaN NaN NaN NaN NaN NaN   NaN   NaN       1.6        1.0       1.65   
3 NaN NaN NaN NaN NaN NaN   NaN   NaN       1.0        0.9       0.70   
4 NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.0       -1.0      -0.80   
5 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0        0.3       0.45   
6 NaN NaN NaN NaN NaN NaN   NaN   NaN       1.8        1.3       0.75   
7 NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.8       -0.6      -1.20   
8 NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6        0.8       0.70   
9 NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.0       -0.5      -1.15   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5  SDiff10  \
0      0.2       0.0     -0.05     -0.6      -0.4     -0.40    5.80     4.00   
1     -0.5      -0.2     -0.45      0.3       0.0      0.65   -3.85    -0.55   
2      1.4       0.5      1.10     -0.8      -0.9     -1.20    9.00     7.90   
3      1.2       0.5      0.50     -0.6      -0.7     -0.70    1.00    -0.20   
4     -0.2      -0.5     -0.40      0.8       0.7      0.55   -5.20    -6.80   
5     -0.8      -0.4      0.25     -0.2      -0.6     -0.45   -4.40    -1.30   
6      2.2       1.5      1.20     -0.2      -0.1     -0.20    6.00     6.00   
7     -1.2      -0.4     -0.70     -1.0      -0.1      0.55    2.20     3.60   
8      0.4       0.7      0.80     -0.6      -0.6     -0.50    5.20     5.20   
9     -0.6      -0.8     -1.55      0.4       0.3      0.50   -4.80    -6.40   

   SDiff20  STDiff5  STDiff10  STDiff20  FDiff5  FDiff10  FDiff20  CDiff5  \
0     2.70     3.20      1.70      0.85     3.8      1.2     1.05    -1.0   
1    -0.05    -2.05     -1.05     -1.65    -0.5     -1.4    -1.70     1.9   
2     6.85     4.80      2.80      2.80    -1.6     -3.8    -2.90     3.6   
3    -1.60    -0.20      0.00     -0.40    -1.6     -2.4    -1.45    -1.2   
4    -6.65    -1.80     -2.10     -2.70     1.2      1.3     0.40    -1.4   
5    -0.40    -1.60     -0.60     -0.10    -1.8     -0.5    -1.90     3.0   
6     7.25     4.40      3.20      2.95    -2.6      0.9     0.85     2.2   
7     2.60    -0.60      0.80      0.40     0.6     -0.2    -0.55     1.8   
8     4.00     1.40      1.10      1.10    -1.2      3.3     2.50     2.6   
9    -7.55    -1.40     -2.60     -3.00    -0.2     -1.8     0.15    -0.6   

   CDiff10  CDiff20  YDiff5  YDiff10  YDiff20  RDiff5  RDiff10  RDiff20  H1  \
0      0.1     0.40    -1.4     -0.6    -0.35    -0.4     -0.2    -0.05   0   
1      1.5     1.20    -0.8     -0.5    -0.50    -0.2     -0.1    -0.10   0   
2      3.0     2.55    -1.8     -1.7    -1.30    -0.2     -0.1    -0.05   3   
3     -1.9    -0.40    -0.2     -0.1    -0.35     0.0      0.0    -0.05   0   
4     -1.7    -1.25    -0.8     -0.2    -0.30     0.4      0.3     0.20   1   
5      2.1     2.00    -2.2     -1.6    -1.30     0.2      0.1     0.00   3   
6      0.9     2.05     1.4      

In [3]:
GW6 = GW6[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW6

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0       0.0        0.1       0.10      0.2       0.0     -0.05     -0.6   
1      -0.6       -0.7      -1.05     -0.5      -0.2     -0.45      0.3   
2       1.6        1.0       1.65      1.4       0.5      1.10     -0.8   
3       1.0        0.9       0.70      1.2       0.5      0.50     -0.6   
4      -1.0       -1.0      -0.80     -0.2      -0.5     -0.40      0.8   
5       0.0        0.3       0.45     -0.8      -0.4      0.25     -0.2   
6       1.8        1.3       0.75      2.2       1.5      1.20     -0.2   
7      -0.8       -0.6      -1.20     -1.2      -0.4     -0.70     -1.0   
8       0.6        0.8       0.70      0.4       0.7      0.80     -0.6   
9      -1.0       -0.5      -1.15     -0.6      -0.8     -1.55      0.4   

   GCDiff10  GCDiff20  SDiff5  SDiff10  SDiff20  STDiff5  STDiff10  STDiff20  \
0      -0.4     -0.40    5.80     4.00     2.70     3.20      1.70      0.85   
1       0.0      0.65   -3.85    -0.55    -0.05    -2.05     -1.05     -1.65   
2      -0.9     -1.20    9.00     7.90     6.85     4.80      2.80      2.80   
3      -0.7     -0.70    1.00    -0.20    -1.60    -0.20      0.00     -0.40   
4       0.7      0.55   -5.20    -6.80    -6.65    -1.80     -2.10     -2.70   
5      -0.6     -0.45   -4.40    -1.30    -0.40    -1.60     -0.60     -0.10   
6      -0.1     -0.20    6.00     6.00     7.25     4.40      3.20      2.95   
7      -0.1      0.55    2.20     3.60     2.60    -0.60      0.80      0.40   
8      -0.6     -0.50    5.20     5.20     4.00     1.40      1.10      1.10   
9       0.3      0.50   -4.80    -6.40    -7.55    -1.40     -2.60     -3.00   

   FDiff5  FDiff10  FDiff20  CDiff5  CDiff10  CDiff20  YDiff5  YDiff10  \
0     3.8      1.2     1.05    -1.0      0.1     0.40    -1.4     -0.6   
1    -0.5     -1.4    -1.70     1.9      1.5     1.20    -0.8     -0.5   
2    -1.6     -3.8    -2.90     3.6      3.0     2.55    -1.8     -1.7   
3    -1.6     -2.4    -1.45    -1.2     -1.9    -0.40    -0.2     -0.1   
4     1.2      1.3     0.40    -1.4     -1.7    -1.25    -0.8     -0.2   
5    -1.8     -0.5    -1.90     3.0      2.1     2.00    -2.2     -1.6   
6    -2.6      0.9     0.85     2.2      0.9     2.05     1.4      1.3   
7     0.6     -0.2    -0.55     1.8      0.8     0.95     0.6     -0.3   
8    -1.2      3.3     2.50     2.6      2.2     0.40    -0.8      0.3   
9    -0.2     -1.8     0.15    -0.6     -1.4    -2.50    -0.4      0.0   

   YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0    -0.35    -0.4     -0.2    -0.05   0   3            0            0   
1    -0.50    -0.2     -0.1    -0.10   0   0            0            0   
2    -1.30    -0.2     -0.1    -0.05   3   1            1            0   
3    -0.35     0.0      0.0    -0.05   0   0            0            0   
4    -0.30     0.4      0.3     0.20   1   0            0            0   
5    -1.30     0.2      0.1     0.00   3   3            0            1   
6     0.30     0.0      0.0     0.00   3   1            0            0   
7     0.20     0.0      0.0     0.00   1   3            0            0   
8     0.45     0.2      0.1     0.05   3   0            1            0   
9     0.45     0.2      0.1     0.10   0   3            0            0   

   HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  HLossStreak3  \
0            0            0             0             0             0   
1            0            0             1             0             1   
2            1            0             0             0             0   
3            0            0             0             0             0   
4            0            0             0             0             0   
5            0            0             0             0             0   
6            0            0             0             0             0   
7            0            0             0             0             0   
8        

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW6_predictions = np.argmax(diff_model.predict(GW6), axis=1)
GW6_predictions

1/1 [==============================] - 0s 475ms/step


array([2, 2, 2, 2, 0, 2, 2, 2, 2, 0], dtype=int64)

In [7]:
diff_model.predict(GW6)

1/1 [==============================] - 0s 62ms/step


array([[2.21149400e-01, 2.40021273e-01, 5.31713307e-01, 1.23637059e-04,
        7.27989463e-05, 9.63081984e-05, 5.86654351e-05, 9.45128268e-05,
        2.40459573e-04, 6.93322145e-05, 7.58187161e-05, 9.88917236e-05,
        8.84139590e-05, 1.04450577e-04, 7.48710445e-05, 8.89046132e-05,
        1.55224901e-04, 1.05031424e-04, 9.52586415e-05, 1.23082587e-04,
        1.20108765e-04, 1.14638759e-04, 8.50053038e-05, 7.72639833e-05,
        1.08266941e-04, 1.69780295e-04, 7.96412351e-05, 9.74449358e-05,
        1.65126097e-04, 5.85706803e-05, 8.12186699e-05, 9.45393331e-05,
        1.70740226e-04, 7.61918709e-05, 1.78914954e-04, 1.37764218e-04,
        1.08869950e-04, 1.14555478e-04, 6.98713266e-05, 1.15969502e-04,
        9.47787339e-05, 9.23702901e-05, 9.52719056e-05, 6.45952750e-05,
        9.33136034e-05, 1.30142042e-04, 5.86439564e-05, 9.90283806e-05,
        9.94453585e-05, 1.36966424e-04, 1.21926932e-04, 6.43790481e-05,
        9.05715933e-05, 1.12589354e-04, 5.50822260e-05, 1.375457

In [8]:
GW6_predictions_2 = np.argmax(diff_model_2.predict(GW6), axis=1)
GW6_predictions_2

1/1 [==============================] - 0s 238ms/step


array([2, 2, 2, 2, 0, 2, 2, 2, 2, 0], dtype=int64)

In [9]:
diff_model_2.predict(GW6)

1/1 [==============================] - 0s 61ms/step


array([[0.22678538, 0.22800747, 0.5452072 ],
       [0.2908732 , 0.3028064 , 0.40632033],
       [0.04506804, 0.12449048, 0.8304414 ],
       [0.2658235 , 0.2639957 , 0.47018075],
       [0.54677206, 0.26137537, 0.19185242],
       [0.17223309, 0.25607044, 0.5716965 ],
       [0.0694738 , 0.1362576 , 0.79426855],
       [0.26583233, 0.28960025, 0.44456747],
       [0.12387435, 0.19125348, 0.68487215],
       [0.6216275 , 0.24648377, 0.13188869]], dtype=float32)

In [10]:
GW6_predictions_3 = np.argmax(diff_model_3.predict(GW6), axis=1)
GW6_predictions_3

1/1 [==============================] - 0s 267ms/step


array([2, 0, 2, 2, 0, 2, 2, 2, 2, 0], dtype=int64)

In [11]:
diff_model_3.predict(GW6)

1/1 [==============================] - 0s 56ms/step


array([[0.13943444, 0.28668937, 0.5738762 ],
       [0.36457172, 0.32542413, 0.31000403],
       [0.08766297, 0.1477956 , 0.76454145],
       [0.26551867, 0.26545706, 0.4690242 ],
       [0.52792954, 0.2539147 , 0.21815579],
       [0.22813648, 0.25518775, 0.5166758 ],
       [0.07380241, 0.11170229, 0.81449527],
       [0.29103643, 0.26543695, 0.4435267 ],
       [0.14888176, 0.23142008, 0.6196981 ],
       [0.51637435, 0.24740805, 0.23621757]], dtype=float32)