In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW8 = pd.read_csv('GW8.csv')
GW8

HomeTeam          AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  \
0           Luton         Tottenham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
1         Burnley           Chelsea  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
2         Everton       Bournemouth  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
3          Fulham  Sheffield United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
4      Man United         Brentford  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
5  Crystal Palace     Nott'm Forest  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
6        Brighton         Liverpool  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
7        West Ham         Newcastle  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
8          Wolves       Aston Villa  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
9         Arsenal          Man City  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   

   AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.8  -1.428571  -1.028571   
1 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.6  -0.400000   0.000000   
2 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.4   0.500000  -0.100000   
3 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.8   0.500000   0.400000   
4 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6   0.200000   0.350000   
5 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6   0.300000   0.450000   
6 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.6  -0.200000  -0.300000   
7 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.0  -0.100000  -0.450000   
8 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.0  -1.400000  -0.900000   
9 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.2  -0.200000  -0.550000   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5   SDiff10  \
0     -1.6 -1.442857 -1.192857      0.2       0.6      0.20    -6.4 -4.642857   
1      0.0 -0.100000 -0.150000      1.6       0.8      0.45    -3.0 -4.600000   
2      0.6  0.300000  0.250000     -0.8      -0.3     -0.10     4.8  4.200000   
3      0.0  0.300000  0.700000     -1.4      -0.4     -0.35    -0.8 -0.300000   
4      0.2 -0.200000 -0.200000      0.2       0.2     -0.20    -0.4  2.000000   
5      0.2  0.000000  0.000000     -0.2      -0.3     -0.50     1.2  4.200000   
6     -0.2  0.000000  0.050000      1.4       0.6      0.50    -0.4  0.000000   
7     -0.8 -0.600000 -0.850000      0.6       0.6      0.50    -5.0 -4.000000   
8     -1.2 -1.400000 -0.850000      0.4       0.7      0.85    -7.0 -2.700000   
9     -0.2  0.100000  0.000000      0.0       0.3      0.65    -3.8 -2.700000   

    SDiff20  STDiff5  STDiff10  STDiff20  FDiff5   FDiff10   FDiff20  CDiff5  \
0 -2.942857     -5.4 -4.514286 -3.564286    -1.0  0.214286  0.064286    -0.6   
1 -3.400000     -1.4 -1.700000 -1.400000    -2.8  0.700000  0.450000     0.4   
2  2.850000      1.6  1.600000  0.950000    -3.8 -1.400000 -0.250000     0.4   
3  1.800000     -0.2  0.300000  1.150000    -0.8 -0.700000 -0.550000     2.2   
4  5.450000      1.2  0.500000  1.350000     0.8  0.900000  0.650000     1.8   
5  3.850000      1.8  1.900000  1.200000    -1.0 -1.000000 -0.900000     0.8   
6  2.800000      1.2  1.600000  1.950000     2.2  0.700000  0.550000    -0.4   
7 -4.350000     -2.6 -1.900000 -1.700000    -1.6 -2.100000 -1.750000    -0.4   
8 -2.350000     -3.6 -2.700000 -1.200000     2.0  1.000000  2.550000    -3.6   
9 -0.500000     -1.4 -0.500000 -0.300000     0.8  0.800000  0.800000     1.8   

    CDiff10   CDiff20  YDiff5   YDiff10   YDiff20  RDiff5  RDiff10  RDiff20  \
0  0.228571  1.028571    -2.6 -1.142857 -0.692857     0.0      0.0    -0.05   
1 -0.100000  0.100000    -0.6 -0.600000 -0.650000     0.2      0.3     0.20   
2  2.200000  0.550000     0.2 -0.200000  0.000000     0.0      0.0     0.10   
3  1.300000  1.100000    -0.2 -0.600000 -0.450000     0.0      0.1     0.00   
4  1.700000  2.500000     0.8  0.200000  0.350000     0.0      0.0    -0.05   
5  0.900000  1.300000    -1.8 -1.700000 -1.050000    -0

In [3]:
GW8 = GW8[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW8

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0      -1.8  -1.428571  -1.028571     -1.6 -1.442857 -1.192857      0.2   
1      -0.6  -0.400000   0.000000      0.0 -0.100000 -0.150000      1.6   
2       0.4   0.500000  -0.100000      0.6  0.300000  0.250000     -0.8   
3       0.8   0.500000   0.400000      0.0  0.300000  0.700000     -1.4   
4       0.6   0.200000   0.350000      0.2 -0.200000 -0.200000      0.2   
5       0.6   0.300000   0.450000      0.2  0.000000  0.000000     -0.2   
6      -0.6  -0.200000  -0.300000     -0.2  0.000000  0.050000      1.4   
7       0.0  -0.100000  -0.450000     -0.8 -0.600000 -0.850000      0.6   
8      -1.0  -1.400000  -0.900000     -1.2 -1.400000 -0.850000      0.4   
9      -0.2  -0.200000  -0.550000     -0.2  0.100000  0.000000      0.0   

   GCDiff10  GCDiff20  SDiff5   SDiff10   SDiff20  STDiff5  STDiff10  \
0       0.6      0.20    -6.4 -4.642857 -2.942857     -5.4 -4.514286   
1       0.8      0.45    -3.0 -4.600000 -3.400000     -1.4 -1.700000   
2      -0.3     -0.10     4.8  4.200000  2.850000      1.6  1.600000   
3      -0.4     -0.35    -0.8 -0.300000  1.800000     -0.2  0.300000   
4       0.2     -0.20    -0.4  2.000000  5.450000      1.2  0.500000   
5      -0.3     -0.50     1.2  4.200000  3.850000      1.8  1.900000   
6       0.6      0.50    -0.4  0.000000  2.800000      1.2  1.600000   
7       0.6      0.50    -5.0 -4.000000 -4.350000     -2.6 -1.900000   
8       0.7      0.85    -7.0 -2.700000 -2.350000     -3.6 -2.700000   
9       0.3      0.65    -3.8 -2.700000 -0.500000     -1.4 -0.500000   

   STDiff20  FDiff5   FDiff10   FDiff20  CDiff5   CDiff10   CDiff20  YDiff5  \
0 -3.564286    -1.0  0.214286  0.064286    -0.6  0.228571  1.028571    -2.6   
1 -1.400000    -2.8  0.700000  0.450000     0.4 -0.100000  0.100000    -0.6   
2  0.950000    -3.8 -1.400000 -0.250000     0.4  2.200000  0.550000     0.2   
3  1.150000    -0.8 -0.700000 -0.550000     2.2  1.300000  1.100000    -0.2   
4  1.350000     0.8  0.900000  0.650000     1.8  1.700000  2.500000     0.8   
5  1.200000    -1.0 -1.000000 -0.900000     0.8  0.900000  1.300000    -1.8   
6  1.950000     2.2  0.700000  0.550000    -0.4 -1.700000 -0.150000     1.0   
7 -1.700000    -1.6 -2.100000 -1.750000    -0.4 -0.300000 -1.100000     0.2   
8 -1.200000     2.0  1.000000  2.550000    -3.6 -2.200000 -1.100000     0.4   
9 -0.300000     0.8  0.800000  0.800000     1.8  2.600000  1.100000    -0.8   

    YDiff10   YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  \
0 -1.142857 -0.692857     0.0      0.0    -0.05   0   3            0   
1 -0.600000 -0.650000     0.2      0.3     0.20   3   3            0   
2 -0.200000  0.000000     0.0      0.0     0.10   0   0            0   
3 -0.600000 -0.450000     0.0      0.1     0.00   0   0            0   
4  0.200000  0.350000     0.0      0.0    -0.05   0   1            0   
5 -1.700000 -1.050000    -0.4     -0.2    -0.10   3   1            0   
6  1.100000  0.550000    -0.6     -0.4    -0.20   0   0            0   
7 -0.400000 -0.150000     0.0      0.1     0.05   3   3            0   
8 -0.400000  0.300000     0.2      0.2     0.15   3   3            0   
9  0.000000 -0.200000    -0.2      0.0     0.00   3   0            0   

   AWinStreak3  HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  \
0            0            0            0             0             0   
1            0            0            0             0             0   
2            0            0            0             0             0   
3            0            0            0             0             1   
4            0            0            0             0             0   
5            0            0            0             0             0   
6            0            0            0             0             0   
7            1            0            0             0             0   
8            1            0            0             0             0   
9

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW8_predictions = np.argmax(diff_model.predict(GW8), axis=1)
GW8_predictions

1/1 [==============================] - 0s 235ms/step


array([0, 0, 2, 2, 2, 2, 2, 0, 0, 2], dtype=int64)

In [7]:
diff_model.predict(GW8)

1/1 [==============================] - 0s 25ms/step


array([[4.42237437e-01, 2.79142559e-01, 2.72092611e-01, 1.33383757e-04,
        5.83805668e-05, 1.03473103e-04, 4.29760039e-05, 5.95904748e-05,
        2.25382493e-04, 7.41930198e-05, 7.36819493e-05, 1.05547238e-04,
        6.80344674e-05, 9.94704023e-05, 9.93295325e-05, 6.96847274e-05,
        2.01888455e-04, 1.02477803e-04, 9.13927579e-05, 1.95624569e-04,
        1.07806998e-04, 1.04189916e-04, 8.10218626e-05, 6.07661968e-05,
        9.38925805e-05, 1.96674548e-04, 4.31878034e-05, 8.32560399e-05,
        1.82068470e-04, 3.44370819e-05, 6.42294690e-05, 1.04181963e-04,
        1.59022995e-04, 6.16397738e-05, 1.71324165e-04, 1.17515920e-04,
        8.39986242e-05, 5.75532977e-05, 4.59808507e-05, 1.01499914e-04,
        8.60685323e-05, 6.06103313e-05, 9.26109133e-05, 7.88902107e-05,
        1.03782433e-04, 9.99067706e-05, 5.57593776e-05, 1.16287345e-04,
        7.35142021e-05, 1.64777652e-04, 9.47091612e-05, 3.10238502e-05,
        1.11146132e-04, 1.02355618e-04, 5.34848114e-05, 8.779253

In [8]:
GW8_predictions_2 = np.argmax(diff_model_2.predict(GW8), axis=1)
GW8_predictions_2

1/1 [==============================] - 0s 176ms/step


array([0, 2, 2, 2, 2, 2, 2, 0, 0, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW8)

1/1 [==============================] - 0s 22ms/step


array([[0.4406375 , 0.30235127, 0.25701118],
       [0.33935177, 0.29768828, 0.3629599 ],
       [0.18994755, 0.24350247, 0.56654996],
       [0.1631794 , 0.21958482, 0.6172358 ],
       [0.12935096, 0.1999615 , 0.67068756],
       [0.13805507, 0.20838435, 0.6535606 ],
       [0.29235134, 0.23733233, 0.47031623],
       [0.45331764, 0.30925405, 0.23742844],
       [0.51678187, 0.24745679, 0.23576128],
       [0.27211908, 0.271338  , 0.45654297]], dtype=float32)

In [10]:
GW8_predictions_3 = np.argmax(diff_model_3.predict(GW8), axis=1)
GW8_predictions_3

1/1 [==============================] - 0s 67ms/step


array([0, 0, 2, 2, 2, 2, 2, 0, 0, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW8)

1/1 [==============================] - 0s 36ms/step


array([[0.51989806, 0.24616466, 0.23393723],
       [0.45322147, 0.32599947, 0.22077893],
       [0.20555408, 0.23746045, 0.55698544],
       [0.18331324, 0.20993938, 0.6067474 ],
       [0.14269403, 0.20397319, 0.65333277],
       [0.18610197, 0.26566818, 0.54822993],
       [0.26616645, 0.27518913, 0.45864442],
       [0.4091193 , 0.2955545 , 0.29532614],
       [0.48457927, 0.26590073, 0.24952008],
       [0.26902387, 0.2666321 , 0.46434397]], dtype=float32)