In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')

In [2]:
GW9 = pd.read_csv('GW9.csv')
GW9

HomeTeam        AwayTeam  FTR  FTHG  FTAG  HS  AS  HST  AST  HF  \
0         Liverpool         Everton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
1       Bournemouth          Wolves  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
2         Brentford         Burnley  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
3          Man City        Brighton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
4         Newcastle  Crystal Palace  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
5     Nott'm Forest           Luton  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
6           Chelsea         Arsenal  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
7  Sheffield United      Man United  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
8       Aston Villa        West Ham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   
9         Tottenham          Fulham  NaN   NaN   NaN NaN NaN  NaN  NaN NaN   

   AF  HC  AC  HY  AY  HR  AR  HPts  APts  PtsDiff5  PtsDiff10  PtsDiff20  \
0 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6        0.8       1.05   
1 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.6       -0.6      -0.20   
2 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.4        0.8       0.35   
3 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -0.2        0.2       0.70   
4 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.4        0.1       0.35   
5 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.4        0.8       0.55   
6 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.2       -1.1      -1.15   
7 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN      -1.0       -1.4      -1.20   
8 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       0.6        0.3       0.60   
9 NaN NaN NaN NaN NaN NaN NaN   NaN   NaN       1.2        1.1       0.55   

   GSDiff5  GSDiff10  GSDiff20  GCDiff5  GCDiff10  GCDiff20  SDiff5  SDiff10  \
0      0.6      1.20      1.10      0.0     0.100    -0.200    -1.8     0.40   
1     -0.8     -0.50     -0.20      0.6     0.000     0.050     3.8     0.50   
2      0.2      0.60      0.40      0.0    -1.000    -0.600     3.8     2.80   
3     -0.2     -0.50      0.05     -1.2    -1.100    -1.050     1.4     0.20   
4      1.8      1.10      1.15      0.0     0.000     0.000     5.0     2.80   
5     -0.2      0.25      0.50     -0.4    -0.775    -0.325    -2.6    -3.05   
6     -1.0     -0.80     -1.15      0.0     0.500     0.200    -1.0     0.40   
7     -0.2     -0.80     -0.75      1.8     0.900     1.100    -5.0    -7.50   
8      0.6      0.30      0.25     -0.6    -0.100    -0.700     5.2     1.40   
9      1.4      1.20      0.85     -0.4    -0.500     0.150     8.2     7.80   

   SDiff20  STDiff5  STDiff10  STDiff20  FDiff5  FDiff10  FDiff20  CDiff5  \
0     0.60     -0.2     -0.10     -0.25     1.2     1.00     1.30     0.4   
1     1.10      1.0      0.60      0.70    -1.0    -1.40    -1.75     2.2   
2     0.55      0.6      0.90      0.80     1.2    -0.60    -0.30    -0.8   
3    -2.35      1.8     -0.40     -0.25    -4.2    -4.40    -3.25     2.0   
4     2.80      1.8      1.50      1.50     2.4     1.00     0.50     1.6   
5    -3.15      0.6      0.95      0.95    -1.2    -1.05     0.00    -2.2   
6     0.40     -0.8     -1.00     -0.90     2.2     0.70    -0.05    -4.2   
7    -9.45     -0.8     -2.90     -3.65     1.8     0.40     1.20    -3.4   
8     1.75      1.2      0.90      0.45     1.8     2.20     1.35     0.8   
9     4.60      3.4      3.60      2.35     0.6     0.50     0.50     2.2   

   CDiff10  CDiff20  YDiff5  YDiff10  YDiff20  RDiff5  RDiff10  RDiff20  H1  \
0     0.40     0.75     0.6    0.500    0.300     0.4      0.4     0.10   1   
1     1.80     0.45    -1.0   -1.100   -0.950    -0.4     -0.3    -0.20   0   
2    -1.40    -1.20     0.8    0.400    0.050    -0.2     -0.3    -0.15   0   
3     0.10     0.20     0.0   -1.300   -0.950     0.2      0.1     0.05   0   
4     1.30     1.10     0.4    1.200    0.150     0.0      0.0     0.00   1   
5    -2.45    -2.60     1.2    0.925    0.775     0.2      0.2     0.10   1   
6    -2.60    -1.15   

In [3]:
GW9 = GW9[['PtsDiff5','PtsDiff10','PtsDiff20',
         'GSDiff5','GSDiff10','GSDiff20',
         'GCDiff5','GCDiff10','GCDiff20',
         'SDiff5','SDiff10','SDiff20',
         'STDiff5','STDiff10','STDiff20',
         'FDiff5','FDiff10','FDiff20',
         'CDiff5','CDiff10','CDiff20',
         'YDiff5','YDiff10','YDiff20',
         'RDiff5','RDiff10','RDiff20',
         'H1','A1',
         'HWinStreak3','AWinStreak3','HWinStreak5','AWinStreak5',
         'HLossStreak3','ALossStreak3','HLossStreak3','ALossStreak5',
         'GDDiff5','GDDiff10','GDDiff20']]

In [4]:
GW9

PtsDiff5  PtsDiff10  PtsDiff20  GSDiff5  GSDiff10  GSDiff20  GCDiff5  \
0       0.6        0.8       1.05      0.6      1.20      1.10      0.0   
1      -0.6       -0.6      -0.20     -0.8     -0.50     -0.20      0.6   
2      -0.4        0.8       0.35      0.2      0.60      0.40      0.0   
3      -0.2        0.2       0.70     -0.2     -0.50      0.05     -1.2   
4       0.4        0.1       0.35      1.8      1.10      1.15      0.0   
5       0.4        0.8       0.55     -0.2      0.25      0.50     -0.4   
6      -1.2       -1.1      -1.15     -1.0     -0.80     -1.15      0.0   
7      -1.0       -1.4      -1.20     -0.2     -0.80     -0.75      1.8   
8       0.6        0.3       0.60      0.6      0.30      0.25     -0.6   
9       1.2        1.1       0.55      1.4      1.20      0.85     -0.4   

   GCDiff10  GCDiff20  SDiff5  SDiff10  SDiff20  STDiff5  STDiff10  STDiff20  \
0     0.100    -0.200    -1.8     0.40     0.60     -0.2     -0.10     -0.25   
1     0.000     0.050     3.8     0.50     1.10      1.0      0.60      0.70   
2    -1.000    -0.600     3.8     2.80     0.55      0.6      0.90      0.80   
3    -1.100    -1.050     1.4     0.20    -2.35      1.8     -0.40     -0.25   
4     0.000     0.000     5.0     2.80     2.80      1.8      1.50      1.50   
5    -0.775    -0.325    -2.6    -3.05    -3.15      0.6      0.95      0.95   
6     0.500     0.200    -1.0     0.40     0.40     -0.8     -1.00     -0.90   
7     0.900     1.100    -5.0    -7.50    -9.45     -0.8     -2.90     -3.65   
8    -0.100    -0.700     5.2     1.40     1.75      1.2      0.90      0.45   
9    -0.500     0.150     8.2     7.80     4.60      3.4      3.60      2.35   

   FDiff5  FDiff10  FDiff20  CDiff5  CDiff10  CDiff20  YDiff5  YDiff10  \
0     1.2     1.00     1.30     0.4     0.40     0.75     0.6    0.500   
1    -1.0    -1.40    -1.75     2.2     1.80     0.45    -1.0   -1.100   
2     1.2    -0.60    -0.30    -0.8    -1.40    -1.20     0.8    0.400   
3    -4.2    -4.40    -3.25     2.0     0.10     0.20     0.0   -1.300   
4     2.4     1.00     0.50     1.6     1.30     1.10     0.4    1.200   
5    -1.2    -1.05     0.00    -2.2    -2.45    -2.60     1.2    0.925   
6     2.2     0.70    -0.05    -4.2    -2.60    -1.15     1.8    1.300   
7     1.8     0.40     1.20    -3.4    -2.70    -3.05     0.4    0.500   
8     1.8     2.20     1.35     0.8     0.50     0.65     1.0    1.000   
9     0.6     0.50     0.50     2.2     1.20     0.00     1.8    0.600   

   YDiff20  RDiff5  RDiff10  RDiff20  H1  A1  HWinStreak3  AWinStreak3  \
0    0.300     0.4      0.4     0.10   1   3            0            0   
1   -0.950    -0.4     -0.3    -0.20   0   1            0            0   
2    0.050    -0.2     -0.3    -0.15   0   0            0            0   
3   -0.950     0.2      0.1     0.05   0   1            0            0   
4    0.150     0.0      0.0     0.00   1   1            0            0   
5    0.775     0.2      0.2     0.10   1   0            0            0   
6    1.300     0.0     -0.1    -0.05   3   3            0            0   
7    0.350     0.2      0.1     0.10   0   3            0            0   
8    1.000     0.0     -0.1    -0.05   1   1            0            0   
9    0.900     0.2     -0.1     0.00   3   3            0            0   

   HWinStreak5  AWinStreak5  HLossStreak3  ALossStreak3  HLossStreak3  \
0            0            0             0             0             0   
1            0            0             1             0             1   
2            0            0             0             0             0   
3            0            0             0             0             0   
4            0            0             0             0             0   
5            0            0             0             0             0   
6            0            0             0             0             0   
7            0            0             1             0             1   
8        

In [5]:
diff_model = load_model('first_diff_model.h5')
diff_model_2 = load_model('second_diff_model.h5')
diff_model_3 = load_model('third_diff_model.h5')

In [6]:
GW9_predictions = np.argmax(diff_model.predict(GW9), axis=1)
GW9_predictions

1/1 [==============================] - 0s 447ms/step


array([2, 2, 2, 2, 2, 2, 0, 0, 2, 2], dtype=int64)

In [7]:
diff_model.predict(GW9)

1/1 [==============================] - 0s 35ms/step


array([[1.81278825e-01, 2.46292159e-01, 5.71193397e-01, 1.44033374e-05,
        1.01986134e-05, 1.56273109e-05, 1.14001632e-05, 1.34831780e-05,
        2.22050840e-05, 1.44109626e-05, 1.95038338e-05, 1.86770449e-05,
        1.76192043e-05, 1.49649941e-05, 1.38098876e-05, 1.48116087e-05,
        5.27919947e-05, 1.17815871e-05, 1.68101506e-05, 2.83291865e-05,
        1.63315835e-05, 3.29436371e-05, 2.51721704e-05, 1.54854533e-05,
        2.64413375e-05, 1.76331050e-05, 1.03567891e-05, 1.38802361e-05,
        1.45630465e-05, 9.71822101e-06, 1.14360091e-05, 2.05180804e-05,
        2.26170341e-05, 1.13107553e-05, 2.59138469e-05, 1.82225849e-05,
        1.62886372e-05, 2.37018849e-05, 9.25973200e-06, 1.36462895e-05,
        1.27954163e-05, 1.14999448e-05, 1.35741229e-05, 1.12472926e-05,
        2.17326760e-05, 1.80149764e-05, 1.66248938e-05, 1.80534826e-05,
        2.03264171e-05, 2.84477410e-05, 2.47409880e-05, 8.11962218e-06,
        1.91074159e-05, 2.59510416e-05, 1.31811821e-05, 2.187189

In [8]:
GW9_predictions_2 = np.argmax(diff_model_2.predict(GW9), axis=1)
GW9_predictions_2

1/1 [==============================] - 0s 145ms/step


array([2, 2, 2, 2, 2, 2, 0, 0, 2, 2], dtype=int64)

In [9]:
diff_model_2.predict(GW9)

1/1 [==============================] - 0s 33ms/step


array([[0.1612796 , 0.22088738, 0.617833  ],
       [0.24297951, 0.27632284, 0.48069757],
       [0.24055989, 0.24810752, 0.51133263],
       [0.2166394 , 0.23772113, 0.5456394 ],
       [0.17958383, 0.22926043, 0.59115565],
       [0.33762357, 0.23414136, 0.42823502],
       [0.43759686, 0.24945886, 0.3129442 ],
       [0.69076395, 0.20906718, 0.10016884],
       [0.20432119, 0.24198963, 0.5536892 ],
       [0.13455747, 0.2295078 , 0.6359347 ]], dtype=float32)

In [10]:
GW9_predictions_3 = np.argmax(diff_model_3.predict(GW9), axis=1)
GW9_predictions_3

1/1 [==============================] - 0s 146ms/step


array([2, 2, 2, 2, 2, 2, 0, 0, 2, 2], dtype=int64)

In [11]:
diff_model_3.predict(GW9)

1/1 [==============================] - 0s 42ms/step


array([[0.17889182, 0.23758608, 0.583522  ],
       [0.30016398, 0.25305715, 0.4467789 ],
       [0.2529668 , 0.25176606, 0.49526706],
       [0.24332637, 0.19613874, 0.56053483],
       [0.1773487 , 0.23713592, 0.58551544],
       [0.36050817, 0.22897033, 0.41052154],
       [0.4518538 , 0.27454388, 0.27360234],
       [0.6024379 , 0.22473346, 0.17282867],
       [0.19426434, 0.2709405 , 0.5347951 ],
       [0.16036452, 0.19580425, 0.64383125]], dtype=float32)